### ISSUE TITLE
QueryParser incorrectly rejects an IRI containing a colon to separate host and port

### ISSUE THREAD

**Issue by benjamingeer** [eclipse/rdf4j#1014]
With `rdf4j-queryparser-sparql` version 2.3.0, an IRI containing a colon to separate the host and port is incorrectly rejected as invalid. This problem does not occur with version 2.2.4.

To reproduce, use an `org.eclipse.rdf4j.query.parser.QueryParser` to parse this SPARQL:

```
PREFIX incunabula: <http://0.0.0.0:3333/ontology/incunabula/simple/v2#>

CONSTRUCT {
    ?book incunabula:title ?title .
} WHERE {
    ?book a incunabula:book .
}
```

This throws the following exception:

```
java.lang.IllegalArgumentException: Invalid IPv4 address U+3A at index 14: http://0.0.0.0:3333/ontology/incunabula/simple/v2#
	at org.eclipse.rdf4j.common.net.ParsedIRI.create(ParsedIRI.java:266)
```

While it is probably uncommon to include port numbers in IRIs stored in a triplestore, we are using the RDF4J SPARQL parser in a SPARQL-based DSL in which we need to be able to do this.

**Comment by aschwarte10** [comment]
We are facing the very same issue in a slightly different context within our application: we are using the HttpRepositoryConfig and provide as endpoint URL some location with an IP address (say 'http://10.212.15.29:8080/openrdf-sesame/repositories/repo').

In our application we use a bootstrap mechanism for repositories and persist the result model of `HtppRepositoyConfig#export` in a turtle file. Parsing such a turtle file with above URL as repository URL will fail.

A minimal test case that reveals the cause is

```
	@Test
	public void testParsedIri() throws Exception {
		
		String iriString = "http://10.212.15.29:8080/openrdf-sesame/repositories/repo";
		ParsedIRI iri = new ParsedIRI(iriString);
		Assert.assertEquals(iriString, iri.toString());
	}
```


A test case for our ttl parsing problem is

```
	@Test
	public void testParseBrokenTtl() throws Exception {
		
		String ttl = "<http://ex.com/s> <http://ex.com/p> <http://10.212.15.29:8080/openrdf-sesame/repositories/repo> .";
		Model m = Rio.parse(new StringReader(ttl), "http://ex.com/", RDFFormat.TURTLE);
		Assert.assertEquals(1, m.size());
	}
```

Note: it looks as setting org.eclipse.rdf4j.rio.helpers.BasicParserSettings.VERIFY_URI_SYNTAX as non fatal error does not help
