### ISSUE TITLE
NativeStore leaks memory with IsolationLevels.SERIALIZABLE

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#1031]
# RDF4J Version

```
<groupId>org.eclipse.rdf4j</groupId>
<artifactId>rdf4j-bom</artifactId>
<version>2.3.1</version>
```

# Script

Execute the attached Java program ([Leak.java.txt](https://github.com/eclipse/rdf4j/files/1983809/Leak.java.txt))

# Expected

A steady memory usage, after the first warm-up iterations, like:

```
 1       4,419
 2       6,442
 3      11,069
 4      11,003
 5      10,965
 6      10,943
 7      10,932
 8      10,933
 9      15,615
10      15,650
11      15,639
12      15,612
13      15,588
14      15,572
15      15,568
```

# Actual

Memory usage steadily increases as performance drops, like:

```
 1      43,717
 2      84,822
 3     124,476
 4     166,430
 5     205,395
 6     245,391
 7     284,710
 8     328,641
 9     369,343
10     408,580
11     447,889
12     487,170
13     526,771
14     566,433
15     606,143
```

# Notes

- works as expected if connection isolation level is reduced to `SNAPSHOT` or not explicitly set;
- transactions are immaterial;
- a differential memory snapshot on a web application affected by the issue revels lots of objects locked in a Changeset referenced by SailSourceBranch at line 464.

![heap dump](https://user-images.githubusercontent.com/6105462/39756757-04baf228-52cb-11e8-98e2-b845244a5927.png)

![heap references](https://user-images.githubusercontent.com/6105462/39756759-0667e7ac-52cb-11e8-844d-8a1d5aae8bda.png)

![code](https://user-images.githubusercontent.com/6105462/39756761-07af8354-52cb-11e8-9a5b-8e63caf8a5c2.png)

**Comment by barthanssens** [comment]
It is still an issue in 3.1.0-snapshot :-(

**Comment by barthanssens** [comment]
There seems to be a huge regression in 3.1.0.
E.g.  running sample program with RDF4J 3.0.4 on OpenJDK 11 (Windows 10):
```
 1      24.342
 2      46.177
 3      67.632
...
13     283.837
14     305.435
15     327.034
```

But with 3.1.0:
```
 1      96.307
 2     207.978
 3     316.410
 ...
13   1.439.022
14   1.548.799
15   1.658.802
```

**Comment by hmottestad** [comment]
@barthanssens if you run this with xmx 1G for 30 runs, does it then run out of memory?

**Comment by jeenbroekstra** [comment]
On my local machine, with 3.0.4 on OpenJDK 11:
```
 1      26,531
 2      48,296
 3      69,851
 4      91,493
 5     113,092
 6     134,691
 7     156,290
 8     177,889
 9     199,488
10     221,087
11     242,686
12     264,285
13     285,884
14     307,483
15     329,082
finished in 17 s
```

3.1.0-SNAPSHOT:

```
 1      97,640
 2     209,275
 3     317,739
 4     432,481
 5     541,464
 6     650,581
 7     759,659
 8     881,079
 9     997,570
10   1,106,231
11   1,214,923
12   1,323,880
13   1,439,280
14   1,548,988
15   1,658,539
finished in 34 s
```

So there's also a big performance regression. When I run with a max heap size of 1G, it grinds to a crawl after finishing the 8th iteration. I killed the run after waiting for ~2 minutes, iteration 9 never printed out.

**Comment by jeenbroekstra** [comment]
@hmottestad  the only thing I can think of that is different between 3.0.4 and 3.1.0 that might be relevant here is the fixes you did in the various Model implementations for concurrent modification exceptions (#1522) - which also touches the MemoryOverflowModel that is used in the transaction handling. Of course, that is not the root cause of the memory leak, but I wonder if those changes have exacerbated the issue. 

Best way forward as I see it is to run some profiling on the master branch, see if we can identify the cause of the original leak, fix it, and then keep our fingers crossed that is also solves the regression on the develop branch.

**Comment by barthanssens** [comment]
I've created a separate ticket for the regression in 3.1.0-snapshot.

**Comment by hmottestad** [comment]
<img width="1338" alt="Screenshot 2020-01-15 at 09 12 34" src="https://user-images.githubusercontent.com/797185/72416540-2d5e1d80-3777-11ea-8ef9-2c338115a22f.png">

This is from debugging the code. It shows that there is a SailSourceBranch that gets reused for every connection/transaction (ie. it has 300 000 statements, but the transaction only adds 100 000). It accumulates the statements in a Model. As @jeenbroekstra points out I swapped out the TreeModel for the LinkedHashModel because the TreeModel does not support multithreaded read operations. I believe the only regression here is that the LinkedHashModel uses more memory for the same number of statements.

**Comment by hmottestad** [comment]
FYI. After some time the MemoryOverflowModel kicks in and overflows to disk. So it never actually runs out of memory, just gets seriously slow.

**Comment by hmottestad** [comment]
<img width="1677" alt="Screenshot 2020-01-15 at 10 49 20" src="https://user-images.githubusercontent.com/797185/72423521-b62f8600-3784-11ea-983d-7d2fc7f50fdf.png">

I've found out that this flush() here **never** gets called if the isolation level is set to serializable (line 344). If you remove the check for serializable==null, then there is no more memory leak. 

If I do remove that serializable==null check though my LongMultithreadedTransactions test deadlocks!

**Comment by hmottestad** [comment]
I'm actually not seeing any issues after removing the check for serializable==null at line 343.

There is unfortunately no git history for that line, so I don't know why there is such a check. Anyone feeling like trying to understand why that line is needed?

**Comment by barthanssens** [comment]
Nice work @hmottestad !
I really have no clue why it would be needed, I've never looked into that much detail into sails/stores :-/

**Comment by jeenbroekstra** [comment]
> I'm actually not seeing any issues after removing the check for serializable==null at line 343.
> 
> There is unfortunately no git history for that line, so I don't know why there is such a check. Anyone feeling like trying to understand why that line is needed?

Currently at work so can't spend too much time on this, but if you want track the history beyond what's available in github, the old sesame repo is still available on bitbucket.org: https://bitbucket.org/openrdf/sesame/

It might be that in the original design flushing had more consequences for transaction isolation, and this was put in as a safeguard. If we remove this and all tests still succeed I'm reasonably in favor of just doing that... I'd like to do some manual tests on a larg-ish dataset to make sure though.
