### ISSUE TITLE
Hierarchical JSON-LD writer

### ISSUE THREAD

**Issue by yasengmarinov** [eclipse/rdf4j#1049]
The current JSON-LD writer can only represent the JSON-LDs triple by triple. The idea behind this enhancement is to be able to represent the JSON-LD objects in a tree-like hierarchical view. Example:
Let's take for example the following 2 tuples:
```
<sch:node1> <sch:pred> <sch:node2> .
<sch:node2> <sch:pred2> <sch:node3> .
```

Output from current JSON-LD writer:
```
[ {
  "@id" : "sch:node1",
  "sch:pred" : [ {
    "@id" : "sch:node2"
  } ]
}, {
  "@id" : "sch:node2",
  "sch:pred2" : [ {
    "@id" : "sch:node3"
  } ]
} ]
```

Same output from hierarchical JSON-LD writer:
```
[ {
  "@id" : "sch:node1",
  "sch:pred" : [ {
    "@id" : "sch:node2",
    "sch:pred2" : [ {
      "@id" : "sch:node3"
    } ]
  } ]
} ]
```
This mode should work with the existing JSON-LD modes - like COMPACT, EXPAND, etc.
The benefit of this mode will be a JSON-LD object which is more human-readable.

**Comment by RavinderSinghMaan** [comment]
@jeenbroekstra @yasengmarinov isn't this same as JSON-LD Framing https://json-ld.org/spec/latest/json-ld-framing/  with embed always?

**Comment by RavinderSinghMaan** [comment]
@yasengmarinov Thanks for the explanation. Actually, the reason I asked this question was that I did something similar. But I extended the method so that it takes starting nodes of graphs. In our use case we needed to return top level resources along with linked resources but embed only once. Using framing one could use embed last option but the problem with type can be still there. So I added optional param which contain list of root node and then hierarchical view will put those node as top level nodes. To make it clear let us say we have below model

```
<sch:node1> <sch:pred> <sch:node2> .
<sch:node1> <sch:pred1> "Node1" .

<sch:node2> <sch:pred> <sch:node3> .
<sch:node2> <sch:pred1> "Node2" .

<sch:node3> <sch:pred> <sch:node2> .
<sch:node3> <sch:pred1> "Node3" .

<sch:node4> <sch:pred> <sch:node1> .
<sch:node4> <sch:pred1> "Node4" .

```
Signature of the interface method

```
String serialise(Model model, List<Resource> topLevelNodes)    
```
Then if topLevelNodes list contains <sch:node1>, <sch:node3> serialisation will be
```
[ {
  "@id" : "sch:node1",
  "sch:pred1" : "Node1",
  "sch:pred" : [ {
    "@id" : "sch:node2",
    "sch:pred1" : "Node2",
    "sch:pred" : [ {
      "@id" : "sch:node3",
     } ]
} ,
{
  "@id" : "sch:node3",
    "sch:pred1" : "Node3",
  "sch:pred" : [ {
    "@id" : "sch:node2"
} ,

]
```

As you can see <sch:node4> is missing. For our use case it never happens but we can provide different options i.e. thror Error , ignore it silently or serialise it as top node.
