### ISSUE TITLE
Remove org.json dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1098]
Current org.json dependency is somewhat outdated, and might not be used at all in some subprojects.

It seems to be used in a few places in the rdf4j-tools subproject for creating XmlHhttpRequests, maybe it can be replaced with a javax.json or com.fasterxml.jackson (which may eliminate this org.json dependency)

**Comment by jeenbroekstra** [comment]
I've just been notified that we never logged a CQ for this dependency. Also, somewhat worryingly: a CQ is likely to not be approved, because this package has a license that is not fully OSS-compatible (in particular, it has a "only use for good not evil" clause in it somewhere).

We should expedite removing this dependency as soon as possible. It may block our next release.

**Comment by jeenbroekstra** [comment]
We may need to cherry pick the fix we do for this and retroactively apply it to some older releases as well, at least the ones that we wish to keep available for download.

**Comment by jeenbroekstra** [comment]
See discussion on https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21981
