### ISSUE TITLE
Upgrade Jetty dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1124]
The RDF4J server is still using Jetty 7.0.2v2010 (released in 2010 and EOL).

The Eclipse Jetty project recommends using Jetty 9.x (Jetty 8 is also EOL), which requires at least Java 8, so the suggestion is to use 9.4.12

**Comment by jeenbroekstra** [comment]
@barthanssens due to the upgrades of Spring and the servlet api  (see #1343) we may need to give this some priority - I am getting test failures with nosuchmethoderrors when running the compliance tests (which still use jetty 7, servlet api 2.5). I'm going to pick this up, let me know if you have any objections or comments :)

**Comment by barthanssens** [comment]
thanks, and of course no objections :-)
