### ISSUE TITLE
Remove the need to initialize a Sail / Repository

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1223]
In the SAIL and Repository APIs, a separate call to `initialize()` is needed to get a usable Sail / Repository object. We should remove the need for this separate call, and just have object initialization happen as and when needed (for example, on the first call to `getConnection()`).

## Note for third party Sail / Repository implementors

This is marked as a breaking change in the API because the API no longer _requires_ a client to explicitly call `init()` (or `initialize()`) before using the Repository or Sail object. Those methods still exist of course, and they _can_ still continue to use them as before - so none of this will break existing client code. All rdf4j-provided `Repository` and `Sail` implementations have been adapted to automatically initialize when necessary. Third party implementations of `Repository` or `Sail` may need to update their code to provide the same functionality. 

Related issues: #552 and #1243

**Comment by jeenbroekstra** [comment]
A possible approach: instead of forcing the user to call `initialize`, we initialize lazily on the first operation on the Repository that requires it (typically, that will be when the user calls `getConnection`).

**Comment by ansell** [comment]
Performing initialisation of things that may generate an exception or that require IO is not encouraged inside of constructors due to the impossibility of cleanup by a user if the constructor doesn't complete successfully and doesn't cleanup its partially constructed resources itself completely. 

Lazily calling `initialize` automatically using a combination of `if(AtomicBoolean.compareAndSet(true, false))` to ensure it only happens once and a `CountDownLatch` to wait on it completing, is something I have done in the past.

**Comment by jeenbroekstra** [comment]
I quite agree that doing this in the constructor is not a good idea. Apart from the reasons you mention it also makes it difficult to deal with any configuration that happens using setter methods. As you say, lazy auto-init on first need is the way forward I think.
