### ISSUE TITLE
SHACL support for < <= > >=

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1253]
https://www.w3.org/TR/shacl/#core-components-range

**Comment by hmottestad** [comment]
@jeenbroekstra @barthanssens I've started working on this and realised it's basically SPARQL filter(?a < ?b), since it needs to support multiple datatypes. Could I get a pointer in the direction of the java code for that feature? Would it be useful to implement the Comparable<> interface in the Literal class?

**Comment by jeenbroekstra** [comment]
Implementing Comparable for Literal is not really advisable I think, see #1063 . However, the algebra has a ValueComparator class for ordering purposes. It, in turn, uses XMLDatatypeUtil to do type-specific comparisons. 

Extending this is something that goes a bit beyond just SHACL though, ideally I'd like something that we can actually use in SPARQL itself - and ideally we can make it configurable so that the StrictEvaluationStrategy sticks to the minimally compliant datatypes only, and the ExtendedEvaluationStrategy allows for additional (custom) datatypes. I haven't really thought this out but I think we should look at some sort of injection mechanism to replace the current fixed util class.

**Comment by hmottestad** [comment]
I’ll take a look at ValueComparator  Thanks.

**Comment by hmottestad** [comment]
I’m just going to use that class you mention. Only difference between the SHACL and SPARQL versions is that the SHACL one should return false for incomparable datatypes. Eg. string vs integer. The SHACL spec being as loosely defined as it is doesn’t specify any more details than that. Not the firste place where they forget to important details that I stumble across during implementation.
