### ISSUE TITLE
Lucene Sail: backward codecs after upgrade

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1256]
Via mailing list https://groups.google.com/forum/#!topic/rdf4j-users/RrrT9F4az_Q

> I've created a native java with lucene rdf4J 2.4.1 repository. 
> It loads data through workbench fine and the lucene index seems to be created. index directory is created.
> However clearing a context through workbench 
> gives the error even though the operation seems to complete.
> org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.lang.IllegalArgumentException: Could not load codec 'Lucene62'. Did you forget to add lucene-backward-codecs.jar?
> I also get the error now on loading data to the repository ( which didn't happen on first load) 
> Once again the operation seems to complete as I see data. 
> 
> I have also looked back to 2.3.2 and I see the lucene-backward-codecs.jar seems to have been included in the rdf4J-server libs directory.
> But it is not present in the 2.4.1 libs directory.

**Comment by jeenbroekstra** [comment]
Unfortunately due to the change in issue tracking (moving to single repo issue tracker) I can't find the full discussion anymore (closed issues weren't migrated and now give 404s 👎). However, in commit https://github.com/eclipse/rdf4j-storage/commit/a52bcf1cd7b215dd77db4235877e7a829072e9a5 we deliberately made the backwards-codec an optional runtime dependency. That means that in a maven build we require people to include it themselves, and also explains why it's not included in the SDK. 

What I would like to understand is why people are reporting they need this library if they are using a _new_ Lucene Sail. 

Also: I guess it would be a good idea to write (or point to) a HowTo on upgrading existing lucene indexes so that this codec is not necessary.

**Comment by barthanssens** [comment]
If I read the mail correctly, it is actually an existing Lucene (5.x) index, accessed or modified after upgrading to a newer rdf4j with Lucene 6.x ...

I've created another ticket (#1255), also reported/suggested by the same user, to check if a console command can be added to re-build an index.

**Comment by barthanssens** [comment]
Related to #1114
