### ISSUE TITLE
Improve performance of statement removal in Native Store

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1425]
Statement removal performance (as well as clear, see #545) is poor in the native store. On running some local tests on a native store of about 10M statements, adding 5k additional statements takes milliseconds, as does querying, but removal of the same amount of statements takes in the order of 20-30 seconds.

Running a quick profiling check indicates that the bottleneck is that `flushPendingUpdates` is called for _every single_ statement removal, even if ran inside a transaction. We should investigate if that can be mitigated.

**Comment by boyarintsev** [comment]
@jeenbroekstra Thanks for looking into this. Am I right that this is already included into 2.5.2 patch release? If so I'm afraid I cannot see any significant performance boost. Still ~20 seconds / 4000 triples. I've run multiple tests with different combinations of transactions, but the result is always the same. I'm probably missing something. You said you were able to reproduce the issue. Is there any chance you could share the simple code / dataset with me so I could compare to my usecase? "Clear()" performance looks the same too.

**Comment by jeenbroekstra** [comment]
I'm not behind the machine I ran this on right now, so can't give you the exact code, but roughly what I did was the following. I created a native store with three indexes (spoc, ospc, posc from the top of my head) with about 9 million triples by minting random subject IRIs (using UUID), and given each of them an rdf:type, an rdfs:label, and an rdfs:comment property. 

To measure query performance I did a simple CONSTRUCT query that retrieves 4000 statements, materialising that result in a `Model` object. On my laptop, repeated runs of that consistently showed response times in order of 10-100ms. I then started a transaction and used `conn.remove(Iterable)` to remove the statements in the model from the store. Measuring of that operation showed 20-30 seconds before the fix, and 200-600ms after.

**Comment by jeenbroekstra** [comment]
I'll post up the exact code I used to test ASAP. Can you, in return, give a code example of how you're executing this as well? If there's a case I have overlooked I'm happy to re-open this issue.

**Comment by boyarintsev** [comment]
Thanks @jeenbroekstra !
I' ve got a tree of Classes:

>                             Parent
>                                 | (subclassOf)
>                        -------------------------
>                        |           |           |
>                       Child1     Child2     Child3
>                         |
>             -------------------------
>             |           |           |
>            Child11     Child12    ChildN

Parent and children have similar structure: it's a Resource with type and label connected with a superclass by subclassOf relation. Every Resource has an incoming relation with object holding a few metadata properties along with it's own type and label. Triples could have a Context or it could be null. In practice very few of them does't have Context (~1% or less) others have the same Context. Children could be nested into children several times. My goal is to remove the whole branch. For example, remove Child1 and everything below it. But these Resources must meet additional conditions (which I check in the code), so I'm not using a single SPARQL query for this.

First I find all children to remove as a flat set:
```
    Set<Resource> children; // Child1, Child11, Child12, ..., ChildN
    Set<Statement> toRemove = new HashSet<>();    
    for (Resource child : children) {
        toRemove.addAll(memConn.getStatements(child, null, null);
        toRemove.addAll(memConn.getStatements(null, null, child);
    }
...
    diskConn.begin();
    diskConn.removeStatements(toRemove);
    diskConn.commit();
```
It's a Native Store with the indexes you've metioned - spoc, ospc, posc.
Maybe it's worth mentioning that I use Memory Store on top of Native Store. I always read from memory and write both into memory and disk. Memory Store is populated on app start with the triples from Native Store. Removals from the Memory Store are fast, the problem is with Native Store only.

**Comment by boyarintsev** [comment]
Also timings show that almost all time was spent during commit:

>Removed 4360 triples
>Remove took: 112
>Commit took: 18169

And reading statements to remove from the memory store doesn't seem to have any negative effect. Since reading from disk store and removing them shows the same result.

**Comment by jeenbroekstra** [comment]
Strange. It's possible the mapping between statements object from a separate memory store and the native store statements has something to do with this. I'll try and see about reproducing over the weekend.

**Comment by jeenbroekstra** [comment]
I can't immediately reproduce this, which means it might be a problem specific to the shape of your data and/or how you've set up this sync between a memory store and a native store. What's your heap size and how much of it is in use, roughly, during the remove operation? Given that you're keeping everything in memory as well, I'm wondering if heap pressure is causing the native store to prematurely overflow to disk while handling the transaction. This would severely slow down the transaction.

Also I notice your  code call `removeStatements`, which indicates that you are using the SAIL API directly, rather than using the Repository API. That shouldn't normally be an issue but it's not recommend. Any particular reason for this approach?

**Comment by boyarintsev** [comment]
Basically we use memory and native store as 2 separate stores and all syncronization is handled by our app logic, so I believe rdf4j should be "unaware" of this sync.
As for the heap, it's a good point. We use >32GB heap (out of 244 server's RAM) on production and it's more than we usually need, so JVM doesn't always work on a peak. But maybe there are still some premature flushes. Could you give me a hint, how I could check this?
As for SAIL API vs Repository API, let me clarify this please. The link 
[https://rdf4j.eclipse.org/documentation/programming/repository/](url)
shows examples very similar to our usage under Repository API header. Do you mean accessing Repository via REST? We use current approach, because some inference logic is handled inside the app, so we send lots of queries, which is way slower via REST.

**Comment by jeenbroekstra** [comment]
> Could you give me a hint, how I could check this?

One way is to use a profiler and check if the core bottleneck in your commit has anything to do with  the method `MemoryOverflowModel#overflowToDisk`. More generally, have a look at heap pressure in the profiler, see how often garbage collection is invoked - if it's often, it's likely thrashing due to churn/insufficient heap.

**Comment by boyarintsev** [comment]
@jeenbroekstra Sorry for the long response. I've created a simple project which I believe reproduces the problem with removals and also SPARQL select I've mentioned in the another StackOverflow thread. I would be glad if you could have a look. I've added you to private Github project. Please, let me know if it works for you or it's necessary to make it public.

The dataset has about 1.4M triples - it's the original dataset, but a bit outdated. The shape of data hasn't changed since then. What's interesting, the timings look similar even though here we have roughly only 20% of the current dataset.

**Comment by jeenbroekstra** [comment]
@boyarintsev thanks for putting this together. I have to give a couple of other issues priority at the moment, but I'll try and get back to this as soon as possible.

**Comment by boyarintsev** [comment]
Thanks!
