### ISSUE TITLE
Allow empty named graphs / contexts

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1456]
The rdf4j APIs currently assume that when a context / named graph contains no more statements, that context no longer exists. There is no support for triplestore implementations that keep a named graph reference until explicitly instructed to drop it (e.g. by means of a SPARQL `DROP` update - which in rdf4j is just translated into a clear because we assume that a clear empties _and_ removes the named graph). 

Apart from better support for third-party databases that have different behavior, it will also allow us to fundamentally improve performance of operations of contexts - the more explicit nature makes caching of context identifiers in, for example, the native store, possible (see #1453 ).

**Comment by jeenbroekstra** [comment]
We may have found a solution for #1453 which makes this enhancement less off a priority. Nevertheless it might be a good idea to add better support for stores that keep empty named graphs.

**Comment by vassilmomtchev** [comment]
I don’t understand the use case fully behind this Issue. I see only troubles and not any significant value. So far, my impression from users migrating from other RDF databases is that they like more the implicit graph management, but maybe I’m wrong. Anyway, the rationale of building indexes is not the same as the implicit graph management. For example, GraphDB implements an optional CPSO index, which works for SPARQL queries and listing all contexts.

Unless the ambition of the issue is as a high as the index in GraphDB, I will go for a special index to serve repositories/<repoId>/contexts endpoint only. It can be implemented as a simple map IRI, count of explicit statements.

**Comment by jeenbroekstra** [comment]
Thanks for your input @vassilmomtchev. I think I'm with you. As said, the initial motivation (more efficient indexing) is less pressing because we have found a different solution there, and the other advantage (triplestore with different default behavior) is, at this point, theoretical only.  We will park this issue until a specific request for such a feature comes in, then we can re-open.
