### ISSUE TITLE
Repository data lost after some time of inactivity

### ISSUE THREAD

**Issue by matentzn** [eclipse/rdf4j#1549]
I have been trying in vain to solve this, maybe one of you has an idea. I 

1. deploy and rdf4j server instance using [docker](https://hub.docker.com/u/yyz1989), 
1. set up a repo (see config below)
1. load a bunch of datasets into it using curl; 
1. run a few sparql queries against it (which return the expected, non-empty results)

All those steps work fine (I can also browse the store with the UI and see what contexts are loaded etc). However, after about 10-30 minutes (I was not able to pinpoint what triggered that), suddenly the triplestore empties itself; 0 statement, 0 contexts left. 

Config: 
```
Repository ID [memory]: Repository title [Memory store]: Query Iteration Cache sync threshold [10000]: Persist (true|false) [true]: Sync delay [0]: EvaluationStrategyFactory [org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategyFactory]: Repository created
```

If you have any idea in which direction to look, I would be very grateful! Thanks all.

**Comment by jeenbroekstra** [comment]
Is the docker container being restarted at some point? Because that would lead to data loss unless you have specifically started the container with a data directory mapped from the host system, like so:

`docker run -d --rm -p 8080:8080 -e RDF4J_DATA=/data -v /opt/rdf4j-data:/data -e JVM_PARAMS="-Xms1g -Xmx8g" yyz1989/rdf4j`

(where `/data` is the directory used inside the docker container, and `/opt/rdf4j-data` is the directory on your host system that that directory is mapped to)

As an aside: the `yyz1989/rdf4` docker image is not maintained by the RDF4J developers. There is another image at https://hub.docker.com/r/eclipse/rdf4j-workbench which is maintained by us.

**Comment by matentzn** [comment]
Thanks @jeenbroekstra 

Good thought; however, the actual database is created by a separate, one-off process (that also populates it). Since the database remains, it must be something else; We noticed that this memorystore.data file is at first nice and large (50MB or so), and then suddenly only 26 bytes (here the result of ls -l in the data directory inside the container). My feeling was that somehow this directory gets emptied, or synced to a different place, a few minutes after it is first created, but this is only speculation. I will switch to your image and see whether maybe this fixes it..

```
-rw-r-----    1 root     root         808 Sep 21 19:52 config.ttl
drwxr-x---    2 root     root        4.0K Sep 21 19:52 lock
-rw-r-----    1 root     root          26 Sep 21 19:52 memorystore.data
```

(PS thanks for the pointer to your image, I am switching to that one).

**Comment by jeenbroekstra** [comment]
That almost sounds as if some sort of crash happened during the sync to disk. Anything of relevance in the server logs?

**Comment by matentzn** [comment]
@jeenbroekstra I cant imagine it has something to do anymore with rdf4j; seems like a problem with the container orchestration to me! Thank you for the help @jeenbroekstra

**Comment by matentzn** [comment]
(P.S.: It was a problem with orchestration (Rancher, Janitor)). Thanks for bearing with me anyways!
