### ISSUE TITLE
DELETE DATA on single triple repo size takes about 2-4 sec (3.0.0) , config Native + RDFS + SPIN

### ISSUE THREAD

**Issue by vujasm** [eclipse/rdf4j#1562]
Hi,

I have created an empty repository Native + RDFS + SPIN, named 'del'

I execute, over Rest API, INSERT DATA, with only one triple in the context:
`insert DATA {Graph <urn:dummy> {<urn:subject> <urn:predicate> <urn:object>}}`
via REST
`POST http://localhost:8080/rdf4j-server/repositories/del/statements?queryLn=SPARQL&update=insert+DATA+%7BGraph+%3Curn%3Adummy%3E+%7B%3Curn%3Asubject%3E+%3Curn%3Apredicate%3E+%3Curn%3Aobject%3E%7D%7D+%3B%0D%0A&infer=true`

that takes milliseconds to finish, which is really great.

Then I execute DELETE DATA, to delete that single triple I inserted before:
`DELETE DATA {Graph <urn:dummy> {<urn:subject> <urn:predicate> <urn:object>}}`
via REST
`POST http://localhost:8080/rdf4j-server/repositories/del/statements?queryLn=SPARQL&update=delete+DATA+%7BGraph+%3Curn%3Adummy%3E+%7B%3Curn%3Asubject%3E+%3Curn%3Apredicate%3E+%3Curn%3Aobject%3E%7D%7D+%3B%0D%0A&infer=true`

and this takes ~40 seconds, which is not acceptable at all.

This is happening with 2.5.3. and 2.5.4. I have not tested the issue on 3.0.0 yet, but there could be the same performance trouble I guess. _(edited: I just tested it on v3 and delete also takes too long to complete.)_

Please note that on plain Native, or Native + RDFS setup,  my example of DELETE DATA takes milliseconds time. Therefore, I guess the issue is only with Native + {RDFS} + SPIN. I have no any SPIN rules in the 'del' repository I created. It's really weird that DELETE DATA on the repository with one triple, takes 40sec to finish.

Could you please take a look and advise the solution?

We use SPIN rules in our project, so we need Native + RDFS + SPIN config.  If you recommend that we switch to SHACL, then please advise how to setup SHACL support in config.ttl of NATIVE + RDFS rdf4j-server. We use rdf4j-server as we want its out of box REST API feature.

Thanks a lot

**Comment by vujasm** [comment]
I now double tested on 3.0.0. Created a new repository from scratch and got ~2-4 seconds time to complete DELETE DATA request to remove that one triple I inserted.
On another repository that has about 2500 statements, my Delete Data example does not go below 4sec; its 4-6sec.

Anyway, please take a look into this issue and provide some hints as such response time scares me 
taking into account  we expect to have 100-200K triples size in an experimental phase of our project.

Thanks for your support!

**Comment by hmottestad** [comment]
Hi @vujasm 

Is it correct that 3.0.0 is 10x faster than 2.5.4? I was the one who optimised the SPIN implementation for 3.0.0 and I also wrote the current RDFS implementation that became the default in 3.0.0.

Both the SPIN and the RDFS implementation are forward chained. This means that every time you add data to it the inferred triples are calculated and store in the database. The new RDFS implementation is considerably faster at this because it only considers the added statements, the previous implementation was a lot slower because it reran all the RDFS rules for all the data every time you added something. I’m not actually sure what the SPIN implementation does, but I believe it reruns all the rules every time you add data (actually flush - which happens when you commit your transaction or when you read after a write).

When deleting data though, they both have to re-infer all their rules again because there is no mechanism for tracking which inferred triples came from where and what your deleted data then actually affects. 

Are you using SPIN only for data constrains or are you using it to infer data? 

Maybe SHACL is a better fit if all you are only using constraints. However I have not created a template that combines both SHACL and RDFS. Would you expect that inferred data from RDFS are considered for the SHACL constrains (E.g. if you have a subPropertyOf rule for ex:surname -> ex:name and a “minCount 1 ex:name” rule then it would be satisfied if you add ex:Peter ex:surname “Parker”)?

**Comment by hmottestad** [comment]
https://github.com/eclipse/rdf4j/issues/1470

**Comment by hmottestad** [comment]
Since you are using SPIN for inference I don’t think SHACL will be a good fit. Our SHACL implementation is tracking the official recommendation (standard) and we will not incorporate any of the non standard spec (eg. SHACL advanced). We have also not implemented the entire SHACL spec yet. 

I can try to look into what is happening during those 2 seconds required for deletion but my gut feeling is that this  time is due to the included default SPIN rules and that there is little we can do to fix it. I believe there is some way of not loading the default rule set, maybe you can look into if this is an option?

If you intend to have a transactional workload with both additions and deletions rather than a more read heavy workload I think the general design of forward-chaining will be the inherit limiting factor.

**Comment by hmottestad** [comment]
And yes. The RDFS implementation will clear out all the forward chained triples during a deletion. So all the forward chaining needs to rerun in its entirety. For additions it is incremental.

**Comment by hmottestad** [comment]
I've verified the behaviour at least.

``
Add statement. Took: 3
Remove statement. Took: 1566
``

Locally on my laptop after 10 iterations or so.

**Comment by hmottestad** [comment]
Some more testing has shown that the RDFS sail is not by itself slow. The SPIN sail is slow (around 1000 ms) and combined with the RDFS sail it becomes even slower (1500ms).

**Comment by hmottestad** [comment]
This is the slowest: `NotifyingSail spinSail = new SchemaCachingRDFSInferencer(new SpinSail(new NativeStore(new File("tempnative"))));
`

**Comment by hmottestad** [comment]
@vujasm Every time you delete something from a SPIN based store it will delete all the inferred statements and add back the base rules and reapply all the rules (the base ones and any that you've added).

The base rules files: https://github.com/eclipse/rdf4j/blob/master/core/spin/src/main/resources/schema/spin-full.ttl

This is what takes so long. 

I don't see there being any way to make this faster.

**Comment by hmottestad** [comment]
Other than this the rules run based on what you add. So adding data that doesn’t match any rules will be very fast. Adding data that matches a rule will still be fast, but it depends on how complex your rule is.

**Comment by vujasm** [comment]
Many thanks @hmottestad . I will let you know how it performs in future, in our case (we will be adding more triples and more rules in our repo. rules are no so complex so far).
