### ISSUE TITLE
Deprecate the LuceneSpinSail

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1692]
Now that SPIN support is being phased out (see #1262 ) we should also deprecate the LuceneSpinSail: 

1. its use case is unclear and undocumented (see #1304) 
2. it is currently a maintenance burden as several SPARQL engine bug fixes are causing test failures in this code

I personally do not have the necessary time or will to fix these test failures. Moving forward, I will mark the LuceneSpinSail module as deprecated, and will disable failing tests unless I see a trivial way to address the problem.

**Comment by hmottestad** [comment]
I think this is good!

For the SpinSail I said the following: "I’m thinking we should mark SPIN as deprecated and just leave it there for the foreseeable future."

For the LuceneSpinSail I think maybe we should go one step further and actually remove it in the next major release, since the issue you linked to says that users are confused about how to use it and there is no documentation.
