### ISSUE TITLE
Allow to use bindings for a FROM clause

### ISSUE THREAD

**Issue by Nyamiou** [eclipse/rdf4j#1714]
It would be useful to be able to create a query like this:

```sparql
select * from ?graph where { ?s ?p ?o .}
```

And set the binding for ?graph. Right now when using a SPARQLRepository this works with a graph query but not a tuple query, and when using a HTTPRepository this doesn't work in both cases.

**Comment by vassilmomtchev** [comment]
Why is there a difference between SPARQLRepository and HTTPRepository implementations?

First of all, the SPARQL query is invalid and must result in a syntax exception. According to the SPARQL, FROM and FROM NAMED clauses, referenced also as Dataset, must be fixed as an IRI and does not accept a variable (see https://www.w3.org/TR/sparql11-query/#rDatasetClause).

The HTTPRepository implementation correctly encodes the query and all its parameters and then result a parse exception. The SPARQLRepository implementation, however, plays it smart and replaces the SPARQL text in the client, so the query become valid.

@jeenbroekstra Do you have any idea why the SPARQLRepository does not encode the values in the same way as the HTTPRepository implementation?

**Comment by jeenbroekstra** [comment]
@vassilmomtchev @Nyamiou the reason this works differently is that the HTTPRepository uses the RDF4J REST API, which allows external variables to be sent along with the request as parameters. So the server receives the original query, and parses it _before_ assigning bindings. This fails because the query is not syntactically legal, and as you correctly obsere @vassilmomtchev , that is the expected behavior.

However, the SPARQL Protocol itself has no facilities to send query bindings as HTTP parameters along with the request. The SPARQLRepository (which cannot use RDF4J-specific extensions) works around this by injecting the bindings into the query string - but it does this by doing simple variable replacement (instead of using something like a VALUES clause). Therefore, the server receives a modified query: 

    select * from <my:binding> where { ?s ?p ?o .}

where as you can see the `?graph` variable has been replaced with an actual value, and it parses it as a legal query. Arguably this is a bug in the SPARQLRepository.

A possible fix would be to ensure that the SPARQLRepository uses `VALUES` clauses as a means to inject bindings, instead of doing simple variable replacement. So the modified query string in this example becomes something like this:

    select * from ?graph where { ?s ?p ?o .  } VALUES ?graph { <my:binding> }

which is not syntactically legal and will cause a parser error (assuming the sparql endpoint correctly implements this of course).

**Comment by jeenbroekstra** [comment]
Related issue: #505
