### ISSUE TITLE
Binding doesn't work in VALUES clause when using HTTPRepository

### ISSUE THREAD

**Issue by Nyamiou** [eclipse/rdf4j#1715]
When trying to use queries like this (just an example we have more complex queries obviously):

```sparql
select * where {?s a ?type . values ?type {?value}}
```

With a SPARQLRepository the ?value get replaced by the binding provided but with HTTPRepository this doesn't work and produce "MALFORMED QUERY: Encountered " <VAR1> "?value """.

If we replace the "values" by "filter" then it works as expected:

```sparql
select * where {?s a ?type . filter(?type in (?value))}
```

**Comment by vassilmomtchev** [comment]
Your intention is probably to send a disjunction of constants and to match at least one of them.

`select * where {?s a ?type . FILTER (?type IN (....)}`

If you bind a variable more than one time, only the last value will remain:

```
String sparql1 = "select * where {?s a ?type. }";			
TupleQuery query = con.prepareTupleQuery(sparql1);
ValueFactory vf = new ValidatingValueFactory();
query.setBinding("type", vf.createIRI("http://example/book1"));
// overrides the previous value
query.setBinding("type", vf.createIRI("http://example/book2"));
```

The only way to overcome this limitation is to generate a query like:

`select * where {?s a ?type . FILTER (?type IN (?var1, ?var2, ?var3)}`

and to bind each value with the respective constant.

**Comment by Nyamiou** [comment]
This was a bad example, sorry, actually our queries are already generated like that (our actual queries are very long and complicated this is just a simple example to help illustrate this issue):
```sparql
select * where {?s a ?type . filter(?type in (?0, ?1, ?2, ?3, ... ?n))}
```
With as many bindings as necessary and then we set their actual value (coming from user input, so unsafe) with setBinding(...). But for optimization purposes, in some cases we wanted to replace FILTER IN by VALUES and so have something like that:
```sparql
select * where {?s a ?type . values ?type {?0, ?1, ?2, ?3, ... ?n}}
```
With again as many bindings as necessary and setting theirs values with setBinding(...). It is our understanding that this should work. With SPARQLRepository this works as expected, the bindings are replaced, but with HTTPRepository we get an error.

**Comment by jeenbroekstra** [comment]
This is closely related to #1714 , actually, and the reason this works in SPARQLRepository but not in HTTPRepository is the same - it is not legal SPARQL syntax to use a variable in a VALUES clause like that. It just happens to work in SPARQLRepository because it does a variable substitution before sending the query to the endpoint, but that is a bug, not a feature, and I would strongly recommend not relying on it. 

There is an open feature request (#505) to allow setting multiple values through a `setBinding` operation. I'll try and prioritize that as it will make cases like these a lot easier to deal with.
