### ISSUE TITLE
Remove IsolationLevel interface

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1785]
The use of a interface doesn't seem to be particularly useful when there is only a single class implementing the interface. It also hinders discoverability since it doesn't play well with code hinting.

**Comment by jeenbroekstra** [comment]
The reason we have this as a separate interface is that third-party stores may choose to implement other, non-standard isolation levels.

**Comment by jeenbroekstra** [comment]
As also suggested on the PR: instead of getting rid of the interface, we can look at removing the need for the enum, and instead have the default isolation levels as static constants on the interface (using an inner class to implement the interface). That way, the interface can still be extended by third parties, while discoverability/autocomplete is improved.
