### ISSUE TITLE
Write tutorial on how to build your own SAIL

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1829]
It would be very useful if we could provide some howto/tutorial-style documentation on creating a custom SAIL. The SAIL architecture can look intimidating, but implementing a simple custom SAIL (for example to use your own choice of database for persistence, or to do some type of reasoning) should not be hard.

**Comment by jeenbroekstra** [comment]
@hmottestad I'm thinking that one thing we could do is use your new ExtensibleStore as the vehicle for this. Perhaps starting with a generic "this is what you need to implement", followed by a "and here's one way we provide some useful defaults to make things easier".

**Comment by hmottestad** [comment]
I am a little bit worried that this would get outdated quickly since I still haven’t implemented write ahead logging. WAL is likely to cause to architectural changes. 

A guide on how to write a sail that handles custom inferencing would also be cool. Essentially a guide to using the notifying sail.

**Comment by jeenbroekstra** [comment]
Fair enough, there is no rush - perhaps once we've had time to get the extensiblestore in a stable state. A first iteration could focus on the basics of the core APIs.
