### ISSUE TITLE
Remote add statements ignores the context when transaction is started 

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#188]
The transaction controller doesn't take into account the context on ADD action. It doesn't parse the contexts like the StatementsController with

```
Resource[] contexts = ProtocolUtil.parseContextParam(request, CONTEXT_PARAM_NAME, vf);
```
this has the effect that any files or statements added through HTTPRepositoryConnection are ignored on the server side.

**Comment by jeenbroekstra** [comment]
I'm not sure I understand the problem. HTTPRepositoryConnection adds statements in a transaction by serializing them into a (binary) RDF file, which includes the context information if present. The TransactionController doesn't process the context parameter because it is assumed to be processed by the parser (when parsing the serialized data), instead. 

Can you outline a simple test case that demonstrates the problem?

**Comment by nikolavp** [comment]
If you try the following:
```java
		StringReader stringReader = new StringReader("<urn:1> <urn:1> <urn:1>.");
		connection.begin();
		URIImpl CONTEXT = new URIImpl("<urn:context>");
		connection.add(stringReader, "<urn:baseUri>", RDFFormat.NTRIPLES, CONTEXT);
		connection.commit();

		URIImpl uri = new URIImpl("<urn:1>");
		assertTrue(connection.hasStatement(uri, uri, uri, false, CONTEXT));
```
on a HTTPRepositoryConnection with and without a transaction, you will see the issue.

Sorry but I am not sure how to simulate a remote repository application in sesame's testcases. Otherwise I am happy to write one.

**Comment by jeenbroekstra** [comment]
Thanks, confirmed. I'm looking into a fix now. There is also a wider issue with other types of update operations within transactions.

**Comment by jeenbroekstra** [comment]
PR up.
