### ISSUE TITLE
Edit SHACL shapes in RDF4J workbench

### ISSUE THREAD

**Issue by aghiran** [eclipse/rdf4j#1899]
I was wondering how can we visualize and edit SHACL shapes in a repository once they had been added. Also, at the moment , in case there is a shape violation all I can get is a rather general validation error and no details regarding what generated that error. Is there a way to see more information? I noticed that in GraphDB is possible to have more insights regarding the shape violation, still what I would like is something similar to what is available online on the shaclplayground.

**Comment by hmottestad** [comment]
Directly in the workbench you can export the shapes graph and you can add or remove shapes by adding or removing statements. SPARQL doesn't work.

Otherwise it's a lot simpler if you use the remote repo in your java code to manipulate it. This should also be faster since you can remove and add shapes in the same transaction.

As for the validation report we have an issue for that https://github.com/eclipse/rdf4j/issues/1900

At the moment it's mostly me working on the ShaclSail, I've been slowly implementing it over the laste few years. All in my spare time, weekends and evenings.

**Comment by aghiran** [comment]
I am using the last version of RDF4J 3.0.4 but I am not able to see the shape statements in the workbench to export them. I can only see the default graph. Also, I am not able to query the SHACLShapeGraph. Once I add them I don't know how can I delete or modify them.

**Comment by hmottestad** [comment]
I actually forgot that I did write some documentation about the SHACL support in Workbench. Take a look at the SHACL section here: https://rdf4j.org/documentation/tools/server-workbench/

**Comment by hmottestad** [comment]
@aghiran did that work for you?

**Comment by aghiran** [comment]
I am sorry, no. Indeed, I wasn't aware of the documentation, I found the URL to download the shapes in it and now I am able to see them. But removing the context SHACLShapeGraph in workbench still doesn't work for me. if I download again the shapes statements I get the same content.

**Comment by hmottestad** [comment]
Could you post some screenshot of what you are trying so I can try to recreate it locally?

**Comment by hmottestad** [comment]
I've verified that this works as documented on master (3.1.x). Remember to include the < and > with the context like this: `<http://rdf4j.org/schema/rdf4j#SHACLShapeGraph>`

**Comment by hmottestad** [comment]
For work on making the validation report available see: #2022
