### ISSUE TITLE
Support SHACL Advanced Features 

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1912]
We should consider adding support for SHACL advanced features - in particular inference rules.  

See https://www.w3.org/TR/shacl-af/

Followup of #1262 

This will require careful design to keep things scalable and performant.

**Comment by hmottestad** [comment]
I don't think it's a good idea to implement any of the inference parts because they lack the fundamental grounding in mathematics that RDFS and OWL has. I also don't like how this was pushed as part of the validation package that SHACL is. I prefer to have a clean validation implementation and a clean inference implementation, keeping them separate but connected so that the validation understands and utilises the reasoner. 

Both our SPIN implementation and our old RDFS implementation are rule based solvers, and suffer greatly when it comes to performance. Our SPIN implementation is also incomplete and incorrect with regards to transactions. This is mainly due to SPIN supporting arbitrary SPARQL and there not being a way to know if your changes affect a SPARQL query without running the query. The SPIN implementation is as fast as it is because it is both incomplete and incorrect. 

From my years experience with semantic tech I have yet to hear about a project that did not suffer horrible performance in one way or another. I've seen projects using SPIN be discarded after years of development. Personally I had to write a new reasoner for RDF4J to be able to use RDFS. And for SHACL we used the Stardog implementation (back when it was called ICV), this ended up giving us 2 TPS (transactions per second) throughput. 

I think arbitrary SPARQL rules have a place in RDF4J since they provide such an amazing wealth of possibility. We should definitely have some sort of SPARQL based reasoner. I don't know if it should be based on SHACL AF or not. I would prefer if it was based on either something that is standardised or something that is mainstream. I don't believe any solution based on SPARQL will be fast though, but it'll still be useful for smaller datasets or infrequent use.

**Comment by jeenbroekstra** [comment]
I'm not necessarily suggesting that support for any of this should be included in the current ShaclSail - like you say validation and inference are different use cases, and though they can possibly share some common functionality they don't need to be the exact same module (in fact I'd prefer them separate). It's early days anyway, I mostly opened this ticket as an early requirements gathering exercise. 

I'm also wary of the unspecific nature of this document - there's a couple of simple examples but little grounding. Having said that I'm not aware of any competing custom inference specification that is both sufficiently standardized and current/maintained/in use in industry. It's 

We could limit ourselves to the triple rules only. From a cursory read this is the simpler form of inference rule (as opposed to full SPARQL rules). 

I'm also thinking of a different way of implementing it - rather than as a "blocking" operation that happens on every transaction of a sail, maybe make it an asynchronous process that just adds inferred data to the store in the background. So we could let go of guaranteeing (immediate) completeness for the sake of speed.

**Comment by hmottestad** [comment]
What do you think our chances are of implementing backwards chaining through query rewrite?

**Comment by jeenbroekstra** [comment]
> What do you think our chances are of implementing backwards chaining through query rewrite?

That might be doable for something like SHACL AF triple rules. I vaguely remember doing a backward chainer years ago to implement basic access control. That never made it into the project (it was an internal bit of code), but it worked pretty well.
