### ISSUE TITLE
Graceful handling of rdf:langString literals without language tag in parser

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2004]
Currently, parsing RDF files which contain literals with an `rdf:langString` datatype, but no associated language tag, fails with an IllegalArgumentException. Setting `VERIFY_DATATYPE_VALUES` to `false` has no influence.

Although RDF4J is strictly speaking correct in reporting this as an error (a literal of type langString _must_ have a language tag), it appears there is sufficient RDF data in the wild with this mistake in it that we should have an option to process it.

Proposed fix: when `VERIFY_DATATYPE_VALUES` is set to `false`, and a `rdf:langString` literal without language tag is encountered, remove the datatype.

**Comment by Mirr99** [comment]
Hi
I would like to contribute to the organisation and start with this issue. Can it be assigned to me?

**Comment by barthanssens** [comment]
Thanks for helping out, it's an open source project, so any help is welcome and much appreciated.

If this is your first contribution to RDF4J, there is one small - but necessary thing - you have to do, because RDF4J is an Eclipse project: register for a (free) Eclipse account and sign a form.

See also "Legal stuff" in https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md

**Comment by Mirr99** [comment]
I have signed the form already. I'll read the document above and make sure I don't miss any other detail out. Thanks for providing the document.

**Comment by jeenbroekstra** [comment]
Thanks for offering to pick this up @Mirr99! 

Just want to offer an upfront pointer that perhaps should have been part of the issue description: it's important to fix this as part of the Rio parser itself, and _not_ do a fix in the ValueFactory classes. The reason I mention this is that there is a very obvious "shortcut" fix, which is just to remove the check in the `createLiteral` method in the AbstractValueFactory. But that is not the intent: the ValueFactory should remain strict about what is a legal language literal.

**Comment by Mirr99** [comment]
Hey,
Are test cases also supposed to be added for this bug or is fixing it enough?

**Comment by jeenbroekstra** [comment]
If you can, adding a test case to avoid regression would be great. A good place would be the `org.eclipse.rdf4j.rio.AbstractParserHandlingTest` (in the `rdf4j-rio-api` module).

**Comment by Mirr99** [comment]
Hi

In order to solve this issue I had made changes to `createLiteral` function in RDFParserHelper.java. This seems to require change in `testCreateLiteralLabelNoLanguageWithRDFLangString` in RDFParserHelperTest.java file as well.

I also added a test case to `org.eclipse.rdf4j.rio.AbstractParserHandlingTest` but that seems to require adding further functions in NTriplesHandlingTest.java, NQuadsHandlingTest.java etc. as well.
For the test case I would need `InputStream` which has rdf:langString literals without language tag. To do this, I was planning to add required files in the different formats and then parsing them. I was unsure of where I should add them. Would the resource folder in the concerned test folder be appropriate?

Thank you

**Comment by jeenbroekstra** [comment]
> In order to solve this issue I had made changes to `createLiteral` function in RDFParserHelper.java. This seems to require change in `testCreateLiteralLabelNoLanguageWithRDFLangString` in RDFParserHelperTest.java file as well.

Seems sensible. 

> I also added a test case to `org.eclipse.rdf4j.rio.AbstractParserHandlingTest` but that seems to require adding further functions in NTriplesHandlingTest.java, NQuadsHandlingTest.java etc. as well.

Not sure why that would be the case - if you add a test case to the abstract class the concrete test classes should just pick it up. Perhaps it will become clearer once you're ready to put up a PR (btw, feel free to put up a PR early if you want feedback, no need to wait until it's "perfect"). 

> For the test case I would need `InputStream` which has rdf:langString literals without language tag. To do this, I was planning to add required files in the different formats and then parsing them. I was unsure of where I should add them. Would the resource folder in the concerned test folder be appropriate?

I think that is a good spot, yes - perhaps a subdir called 'testcases' or something within it to keep things organized.

**Comment by Mirr99** [comment]
> > I also added a test case to `org.eclipse.rdf4j.rio.AbstractParserHandlingTest` but that seems to require adding further functions in NTriplesHandlingTest.java, NQuadsHandlingTest.java etc. as well.
> 
> Not sure why that would be the case - if you add a test case to the abstract class the concrete test classes should just pick it up. Perhaps it will become clearer once you're ready to put up a PR (btw, feel free to put up a PR early if you want feedback, no need to wait until it's "perfect").
> 
So for instance we have `protected InputStream getKnownLanguageStream` defined in `org.eclipse.rdf4j.rio.AbstractParserHandlingTest` and then this function is overwritten in NTriplesHandlingTest.java, NQuadsHandlingTest.java etc.
I was planning to take a similar approach to define a function `protected InputStream getNoLanguageWithRDFLangStream` and then overwriting it. That is what I meant by adding further functions.

Thank you for the advice. I will put up the PR soon.
