### ISSUE TITLE
SHACL report - actual and expected

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2019]
This is an out of spec proposal. `sh:actual` and `sh:expected` are not part of the SHACL standard.

When a shape validation fails, the report should inform the user why it failed in the same way that we do with junit tests.

For a minCount shape with minCount=2 a violation could be:
```
    ...
    sh:expected 2;
    sh:actual 1;
    ...
```

For a datatype shape with datatype=xsd:integer a violation could be:
```
    ...
    sh:expected xsd:integer;
    sh:actual xsd:double;
    ...
```

For a class shape with class=foaf:Person a violation could be:
```
    ...
    sh:expected foaf:Person;
    sh:actual ex:Dog, ex:Bulldog;
    ...
```

Some of these could be produced based on the data already available, while others (like the one for the class shape) would need to gather extra data to show the correct `sh:actual` value.

**Comment by rdstn** [comment]
Going off spec isn't great, but the spec is a bit murky here. Validation reports leave some flexibility to their users.

The result message, for example, is not constrained to a particular format. `sh:expected` can be a part of it.

`sh:actual` is a superset of `sh:value`, where you seem to include all problematic values rather than only one.

Basically, if we want to adhere to the spec, we can fit the `sh:expected` and `sh:actual` functionality within it. If not, what you have suggested sounds much cleaner and I'm all for it.
