### ISSUE TITLE
Query optimiser does not account for already bound variables

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2048]
When reordering joins the documentation says:

Selects from a list of tuple expressions the next tuple expression that should be evaluated. This method selects the tuple expression with highest number of bound variables, **preferring variables that have been bound in other tuple expressions over variables with a fixed value**.

https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/QueryMultiJoinOptimizer.java#L174

While in getTupleExprCardinality(...) the section that accounts for already bound variables is commented out.

```
// Prefer patterns that bind more variables
// List<Var> distinctUnboundVars = getUnboundVars(new
// HashSet<Var>(vars));
// if (distinctUnboundVars.size() >= 2) {
// cardinality /= distinctUnboundVars.size();
// }
```

https://github.com/eclipse/rdf4j/blob/e2190d8a7660cbf57ff81f9e6ed03556b5693925/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java#L424

Git history is missing :(

<img width="1607" alt="Screenshot 2020-03-28 at 17 15 17" src="https://user-images.githubusercontent.com/797185/77827741-b8647800-7117-11ea-8a97-10f937f402ee.png">

**Comment by hmottestad** [comment]
@jeenbroekstra any chance you could shed some light on this?

**Comment by jeenbroekstra** [comment]
That has been commented out since its initial commit in 2008, see https://bitbucket.org/openrdf/sesame/annotate/master/core/queryalgebra/evaluation/src/main/java/org/openrdf/query/algebra/evaluation/impl/QueryJoinOptimizer.java?at=master&fileviewer=file-view-default 

The preference of pattern with more bound values is coded above that, on lines 406-409. Then on lines 417-418 a further adjustment is made to give preference to patterns where unbound vars are also used in other patterns.

**Comment by hmottestad** [comment]
Can I just remove that code then?

**Comment by jeenbroekstra** [comment]
> Can I just remove that code then?

Sure, go for it.
