### ISSUE TITLE
RIO should cope with UTF-8 BOM

### ISSUE THREAD

**Issue by VladimirAlexiev** [eclipse/rdf4j#2099]
RIO doesn't handle UTF-8 BOM (https://en.wikipedia.org/wiki/Byte_order_mark).
A typical error is `Expected ':', found '»' [line 1]`

Jena's implemented this in 2010: https://issues.apache.org/jira/browse/JENA-14

**Comment by jeenbroekstra** [comment]
Sesame implemented this quite a while back as well: https://openrdf.atlassian.net/browse/SES-1830. We're _almost_ as good as Jena, really.

It's always possible there's a lingering bug somewhere of course. Can you give us an example file / test case that demonstrates the problem? In particular: _which_ Rio parser is giving you trouble? Turtle? RDF/XML?

**Comment by jeenbroekstra** [comment]
I just noticed the mention on the commit to the Turtle file in your github repo, so I assume that file's the culprit. 

I just tried to parse that file (the revision before your last commit, so still with the BOM) with Rio 3.1.3 and it worked without a hitch:

		String url = "https://raw.githubusercontent.com/VladimirAlexiev/soml/6e5340cf25278f9de3ecb6985c15f4b44766da33/owl2soml/eg/gvp.ttl";

		Model m = Rio.parse(new URL(url).openStream(), url, RDFFormat.TURTLE);

Perhaps the problem is in the way you invoke the parser, can you provide a code sample?

**Comment by VladimirAlexiev** [comment]
Thanks @jeenbroekstra ! I'll get Yasen Marinov to comment.

**Comment by yasengmarinov** [comment]
Hi Jeen, here is the methods I've written:

```  
private String readFile(String fileName) throws IOException {
    String content = new String(Files.readAllBytes(Paths.get(fileName)));

     return content;
 }

public static Model parseFile(String content, String fileName) throws IOException {
    RDFFormat rdfFormat = Rio.getParserFormatForFileName(fileName).orElse(RDFFormat.TURTLE);

    return Rio.parse(new StringReader(content), "http://example.com", rdfFormat);
  }
```
The RIO version is 3.1.2

**Comment by jeenbroekstra** [comment]
Ah, thanks @yasengmarinov , @VladimirAlexiev . 

The problem here is that this code:
 
     String content = new String(Files.readAllBytes(Paths.get(fileName)));

converts the bytes from the file into a String, using the platform default encoding. This is problematic for two reasons:

1. your platform encoding might be different from the actual file encoding (for example, Turtle files are always UTF-8, but your platform encoding on windows might be something like CP-1252);
2. even if it gets the encoding correct, converting the byte array to a string is normally where you handle the BOM. Since you are doing a naive conversion without taking the BOM into account, the marker bytes get converted into one or more characters at this point. The Rio parser therefore does not receive a BOM, it receives a character stream containing a character that is illegal, so it correctly reports an error. 

There are several ways to fix this. The simplest solution would be to open an InputStream to the file and pass that InputStream along to the Rio parser directly, instead of creating a String and then a StringReader first. I should also point out that, especially for large files, this is more efficient as well since you won't need to keep the full file contents in main memory as a string:

    RDFFormat rdfFormat = Rio.getParserFormatForFileName(fileName).orElse(RDFFormat.TURTLE);
    return Rio.parse(new FileInputStream(fileName), "http://example.com", rdfFormat);

If for some reason you definitely need to convert to a String first, you could use `org.apache.commons.io.input.BOMInputStream` and `IOUtils` (both part of apache commons-io), for example like this:

		BOMInputStream bom = new BOMInputStream(Files.newInputStream(Paths.get(fileName)));
		String content = IOUtils.toString(bom, StandardCharsets.UTF_8);

 You can of course also use Rio to read an RDF file and get it as a Java String, for example like this:

		ByteArrayOutputStream boas = new ByteArrayOutputStream();
		RDFParser parser = Rio.createParser(RDFFormat.TURTLE);
		RDFWriter writer = Rio.createWriter(RDFFormat.TURTLE, boas);

		parser.setRDFHandler(writer); 
		parser.parse(new FileInputStream(fileName), "");

		String content = boas.toString(StandardCharsets.UTF_8);

**Comment by jeenbroekstra** [comment]
Hope that helps. Let me know if this solves the problem for you.

**Comment by yasengmarinov** [comment]
Hi Jeen, thanks a lot. I don't know why I always assume everything is in UTF-8...
