### ISSUE TITLE
Expose if "rightArg is out of scope for leftArg" as part of the query plan

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2119]
https://github.com/eclipse/rdf4j/blob/bc0c94725fc96b735c5521a371c8df84b7424515/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/JoinIterator.java#L74

When the JoinIterator decides that the rightArg is out of scope of the leftArg this means that we join using merge instead of essentially creating a new query from the rightArg for every result that leftArg produces.

When this happens it is important to expose in the query plan because it usually means that performance will be bad if rightArg produces enough results.

**Comment by hmottestad** [comment]
See https://github.com/eclipse/rdf4j/issues/2110

**Comment by jeenbroekstra** [comment]
See also #2140. I'm considering moving this choice out of the JoinIterator class, and making the decision in StrictEvaluationStrategy instead. We already do this for subqueries (where we use a Hash join algorithm instead of the regular interleaved join), and I think it's a cleaner desing (I also can't think of why we aren't using hash join in any case, as we introduced it precisely because of this kind of scoping problem).

**Comment by jeenbroekstra** [comment]
Given the changes we made to how the join strategy decision works, is this issue still relevant? The query plan will now at least show the type of join iterator, which is good clue that a scoping issue caused a particular strategy to be chosen.

In any case: I don't expect that you will do a fix for this in time for 3.2?

**Comment by hmottestad** [comment]
I had an idea for adding a "new scope" label to plan nodes to introduce a new scope.
