### ISSUE TITLE
ParsedIRI#parseHost fails unexpectedly

### ISSUE THREAD

**Issue by kenwenzel** [eclipse/rdf4j#2179]
The following code fails with RDF4J 3.1.2:

```
import org.eclipse.rdf4j.common.net.ParsedIRI;

public class Test {
	public static void main(String[] args) {
		System.out.println(ParsedIRI.create("bundleresource://385.fwk19480900/test.ttl"));
	}
}
```

I think the parseHost method is wrong or too restrictive.
Maybe it would be sufficient to just extract the host instead of parsing it as in:
[https://github.com/eclipse/emf/blob/1ddada6302029e35b02cd0c29704d668d3cdff22/plugins/org.eclipse.emf.common/src/org/eclipse/emf/common/util/URI.java#L3411](https://github.com/eclipse/emf/blob/1ddada6302029e35b02cd0c29704d668d3cdff22/plugins/org.eclipse.emf.common/src/org/eclipse/emf/common/util/URI.java#L3411)

**Comment by kenwenzel** [comment]
Maybe you can also just use EMF's implementation instead of ParsedIRI?

**Comment by jeenbroekstra** [comment]
This fails because `385.fwk19480900` is not a valid host identifier: it's neither an ip literal, nor a valid top-level domain (TLDs are not allowed to start with a number). 

That being said, the restriction on the TLD being valid may be somewhat beyond what RFC 3987 mandates, at least for non-standard schemes. 

> Maybe you can also just use EMF's implementation instead of ParsedIRI?

Unfortunately the URI class you link to is severely out of date - it is still based on the (now obsolete) RFC 2396, which was superceded by RFC 3986, which in turn was extended by RFC 3987 for internationalization purposes.

**Comment by kenwenzel** [comment]
Thank you for looking into this!
