### ISSUE TITLE
Allowing for limiting the size of the validation report associated with a ValidationException

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#2240]
User interfaces for interactive RDF editing/management (e.g. the RDF4J workbench) should display the validation report associated with validation exceptions. This report is usually small because of the small amount of data being affected by the transactions initiated by humans.
However, there are cases in which the size of the report can be big: e.g. the user loaded a huge file or the user executed a SPARQL update affecting a lot of data.
In such cases, retrieving the entire validation report (possibly from a remote server) and displaying it in the user interface (e.g. in a simple error dialog) can be overwhelming.
The solution is a mechanism to limit the size of the validation report so that:
* the report can be displayed in the user interface (without the risk to overwhelm it)
* there is no need to fetch the part of the report that will not be displayed
It should be possible to recognize that the report was truncated.
Morevoer, the solution shall work both on remote RDF4J servers and on embedded repositories.
---

Initially reported on the rdf4j-users mailing list: https://groups.google.com/d/msg/rdf4j-users/v60sFnYsqEc/rSRQunwlAQAJ

**Comment by jeenbroekstra** [comment]
I think this feature comes apart in several requirements: 

1. it should be possible to limit the size of the validation report model at the level of the ShaclSail.
2. the validation report model should include info that it was truncated (can be as simple as adding an `rdf4j:truncated true` property to it). 
3. we should have a mechanism between client and server to indicate if the client wishes to receive a truncated or full report.

None of this _requires_ that the validation report can be retrieved in a streaming fashion, but if you want to tackle that aspect of it: given that the validation report is itself just an RDF document, the server already has plenty of existing code to handle streaming responses over HTTP, (`org.eclipse.rdf4j.http.server.repository.statements.ExportStatementsView` is a simple example) - it typically just comes down to directly serializing to the ServletResponse's OutputStream object. Chunked transfer encoding is pretty much handled automatically IIRC. So that aspect of the transfer is not something we should need any new code for - it's mainly just about getting the report data out of the shacl sail as a lazy Iteration instead of a (materialized) Model.

**Comment by hmottestad** [comment]
Here is the initial conversion of the stream of violations into a list: https://github.com/eclipse/rdf4j/blob/d18f9e02ef39335b30928499d59ab04f318e8bfc/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java#L373

**Comment by hmottestad** [comment]
Here:

https://github.com/eclipse/rdf4j/blob/d18f9e02ef39335b30928499d59ab04f318e8bfc/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java#L422

And here:

https://github.com/eclipse/rdf4j/blob/d18f9e02ef39335b30928499d59ab04f318e8bfc/core/sail/shacl/src/main/java/org/eclipse/rdf4j/sail/shacl/ShaclSailConnection.java#L431

Are the second stage conversion to lists.

**Comment by hmottestad** [comment]
You can fiddle with how many violations each shape can return in the first one, and in the two second ones you can change how many violations are returned in total.

**Comment by hmottestad** [comment]
@VladimirAlexiev you had proposed "shaclErrorLimitGlobal" and "shaclErrorLimitPerConstraintPerShape". I'm currently leaning towards at least using "ValidationResult" and I prefer "truncate" over "limit". So I'm trying out:
```
sail.setValidationResultTruncationTotalSize(...);           // max number of ValidationResults per ValidationReport
sail.setValidationResultTruncationPerConstraintSize(...);   // max number of ValidationResults per constraint component per shape
```

What do you think? Is that understandable? Im not that happy with using "size" though to be honest. Would be great with some feedback from @jeenbroekstra  @manuelfiorelli too!

I have a PR open if anyone want's to see how this looks: https://github.com/eclipse/rdf4j/pull/2334

I'm also planning on going with `rdf4j:truncated true` in the ValidationReport.

For backwards compatibility the default needs to be -1 (unlimited), but GraphDB could have different defaults if you wish.

**Comment by jeenbroekstra** [comment]
First of all, I don't think we should have public setters for all this kind of config stuff on the sail object itself. I would prefer that we first push on the development of #2322 so that we can communicate such settings through a ConnectionConfig object instead having to work directly with the ShaclSail object. 

Although I am not a fan of rolling out features where we know in advance that it's not the final design, I appreciate that timing-wise we may have to do it this way around, in which case we should mark these setter methods as experimental and likely to be removed/hidden again in a future version. I want it made _very_ clear that this is not the recommended way of interacting with the Sail and it's only provided as a temporary workaround until we have the proper configuration mechanism in place.

With that in mind, naming becomes less critical, but I'd still prefer something a bit shorter. How about:

     setMaxValidationResults
     setMaxValidationResultsPerShape

**Comment by hmottestad** [comment]
Would still have the normal rdf based config too, so naming is important. “Max” could be confused with “maxCount” from SHACL, so not that sure about that.

**Comment by hmottestad** [comment]
I like the last one. Limit does seem better now that I’ve had a chance to think about it a bit. 

I still prefer “PerConstraint” instead of “PerShape” since the limit isn’t per shape but per constraint. Eg. a shape could have minCount 1 foaf:age, maxCount 1 foaf:age, datatype foaf:age = xsd:integer; and the limit would hold for each constraint and not for all the constraints for that shape. If the limit was 10 we would produce up to 30 results.

**Comment by manuelfiorelli** [comment]
Hi @hmottestad 
first of all, I apologize for not having contributed to this issue more actively: as a I said on the ML, I'm quite busy in this period. However, I'm really happy to see that this issue has been processed anyway. 

I like the second proposal contained in by @jeenbroekstra , while agreeing with  @hmottestad  that it is better to use `constraint` over `shape`, if the limit applies to each constraint in a given shape.

**Comment by VladimirAlexiev** [comment]
I'm ok with any of the naming options proposed.
- "initial conversion of the stream of violations into a list": @hmottestad please confirm that rdf4j is not generating errors that it later throws out. It should keep a running count and when the limit is reached, should stop generating errors
- will there be a way to set this with config files? I prefer `repo.ttl` (sorry, not sure what's the proper name for this, in Jena it's called "assembler") than eg repo.properties.
- `-1` means "unlimited" and `0` means "don't output"?
  - Then `setValidationResultsLimitTotal=0` will in effect disable validation? There's no point to run any validation if zero results will be output. So there's some overlap with the option to enable validation? That's ok, just needs to be documented well

**Comment by hmottestad** [comment]
@VladimirAlexiev 

I think I might have forgotten to test `0`. It's supposed to mean, validate but return an empty report with only "sh:conforms". 

The parallel validation makes it hard to stop once we've reached the total limit. To create a good solution for this we would need to implement full streaming support. As a stop gap I've added a rule that `validationResultsLimitPerConstraint = Math.max(validationResultsLimitPerConstraint, validationResultsLimitTotal)` so setting just `validationResultsLimitTotal` will also act as an upper limit for `validationResultsLimitPerConstraint`. 

These settings and pretty much all the other ShaclSail settings are available through the standard rdf4j config approach (eg. the turtle based config files).
