### ISSUE TITLE
Potential mistake in RDFCollections.java

### ISSUE THREAD

**Issue by prince17080** [eclipse/rdf4j#2256]
In RDFCollections.java, on [this](https://github.com/eclipse/rdf4j/blob/80ad63a3b2d210cd966ef105fdf848c738cc1d4f/core/model/src/main/java/org/eclipse/rdf4j/model/util/RDFCollections.java#L255) line, in `consumeValues` method, a lambda function is created which only adds a statement if its predicate is `rdf:first`. 

However, on [this](https://github.com/eclipse/rdf4j/blob/80ad63a3b2d210cd966ef105fdf848c738cc1d4f/core/model/src/main/java/org/eclipse/rdf4j/model/util/RDFCollections.java#L338), in the `extract` method, it is trying to add a rdf statement having predicate `rdf:type`. 
Eventually, this line of code is getting ignored by the above lambda function.

Same for [this](https://github.com/eclipse/rdf4j/blob/80ad63a3b2d210cd966ef105fdf848c738cc1d4f/core/model/src/main/java/org/eclipse/rdf4j/model/util/RDFCollections.java#L346) line, it is trying to add a rdf statement having predicate `rdf:rest`.

**Comment by prince17080** [comment]
If it is indeed an issue, we (me, @reeshabhkumarranjan, @guvi007) would like to work on this.

**Comment by jeenbroekstra** [comment]
The `consumeValues` method is intended to retrieve the actual list members and send them to the consumer. So for its purposes, only statements with `rdf:first` are relevant (because those are the ones that have the actual list member values). It ignores everything else because it's not relevant to what it's trying to do.

The `extract` method, however, is about retrieving the entire RDF collection structure. So it's not just about the `rdf:first` triples, but everything: the `rdf:rest` linking statements, and also, if present, the type statement. It tries to retrieve _all_ triples that together form the collection. 

Keep in mind that both are public utility methods. You are of course correct that we could change the `extract` method to not send the type statement, and the `consumeValues` would still work (because it doesn't need it), but other uses of extract (for example, code that uses it to modify or even delete the collection) could depend on the type statement being sent if it is present in the data.

**Comment by jeenbroekstra** [comment]
@prince17080 I'll close this issue now because I think I've answered your question, but if something is still unclear, please free to re-open and comment further.
