### ISSUE TITLE
Formatting script

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2259]
We now have three maven based formatters. We need some way of easily calling all three. I’m currently using an alias, but maybe a script will be easier too run for other developers.

**Comment by jeenbroekstra** [comment]
Can you clarify what you need? First of all, I only count two formatters: the actual formatter plugin, and the import sorting plugin. You can, if you want, manually run them both by just doing

`mvn formatter:format impsort:sort`

However, unless I've made a mistake in the setup, they are automatically run when you invoke any maven command that involves the `process-resources` phase (so `mvn compile`, `mvn verify`, `mvn  package`, `mvn install`, etc) so there's nothing you should need to do. 

If we can make things somewhat easier to use I'd like to hear it, but I'm not in favor of introducing loads of custom build scripts in the code base. It kind of defeats the purpose of using a framework like maven.

**Comment by jeenbroekstra** [comment]
I just realized you probably meant the xml formatter as the third one. It's not automatically activated because I noticed that it does some weird stuff with headers in some cases, and in any case I we don't edit xml so regularly that I thought it necessary to make this an automated process - the guidelines for xml are fairly simple and any editor can be easily tweaked to follow.

**Comment by jeenbroekstra** [comment]
Somewhat related, I just noticed that there is a mistake in how the maven plugins have been configured. Running from the command line, formatting still runs `validate` rather `format` as the target, which means it fails with an error, rather than just fix formatting issues.

**Comment by hmottestad** [comment]
I’ve been using the xml formatter with every pr now for a month or two. I think it should be part of the standard verification step in the GitHub CI. 

This potential script is trying to simplify life for new developers, but I had an idea that maybe we should just include the three formatter calls in the PR template.

**Comment by jeenbroekstra** [comment]
> I’ve been using the xml formatter with every pr now for a month or two. I think it should be part of the standard verification step in the GitHub CI.

That's something we can do.

> This potential script is trying to simplify life for new developers, but I had an idea that maybe we should just include the three formatter calls in the PR template.

To be honest, I prefer encouraging developers to actually update their editor settings and
informing them about the maven build phases, rather than rely on custom scripts. But perhaps we could at least make it clearer what maven calls to use to run this in the PR template. In fact, the simplest is probably just `mvn process-resources` - which runs all the prep-work right up to just before compilation, including the formatting. Takes less than 2 minutes to run on the entire project.

Looking at the PR template, we could add a list item to say "I've applied correct code formatting", putting a link to the code formatting guidelines in there. We should probably also add a generic "contribution guidelines" link in there.
