### ISSUE TITLE
Adjust code format rules for trailing `)` and multiline arguments

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2303]
Multiline arguments can be useful to make code with many wrapped calls more readable.

Currently the following:

```
PlanNode select = new Unique(
	new Sort(
		new TrimTuple(
			new UnorderedSelect(
				connectionsGroup.getAddedStatements(),
				null,
				null,
				null,
				UnorderedSelect.OutputPattern.ObjectPredicateSubject
			),
			0,
			1
		)
	)
);
```

Gets converted to:

```
PlanNode select = new Unique(
		new Sort(
				new TrimTuple(
						new UnorderedSelect(
								connectionsGroup.getBaseConnection(),
								null,
								null,
								null,
								UnorderedSelect.OutputPattern.ObjectPredicateSubject),
						0,
						1)));
```

It would be nice if the code formatter respects when `)` is on a new line. Would also be nice if it didn't indent with two tabs, but I'm ok-ish with that.

**Comment by hmottestad** [comment]
@jeenbroekstra do you agree with this?

**Comment by jeenbroekstra** [comment]
We can probably fix both the indentation and the wrapping for this - though if we change these settings (which are very generically applicable to _all_ method invocations, lambda functions etc) it's possible that code in other situations starts looking weird. 

Another reason I'm hesitant is that it makes it even harder to explain how we expect people to format the code. Our contribution guidelines say that we basically use Eclipse code conventions with a few minor tweaks, but we're getting further away from that with every customization we do. 

I don't necessarily mind losing that connection, but it does mean that we'll need to change our contributor's guide. 

Also: timing. I suggest we wait until there is not as many open/active pull request before we apply this, to avoid getting into merge conflict hell.

**Comment by hmottestad** [comment]
No rush :) I also don’t want this to affect existing code. I just want the formatter to respect if I put the “)” on the next line on purpose. I’m a bit used to the lenient formatter in IntelliJ.

**Comment by jeenbroekstra** [comment]
> No rush :) I also don’t want this to affect existing code.

That is not possible with the current setup. The formatter automatically runs against all existing code. As soon as we change the formatting rules, we will _have_ to reformat the entire code base to fit it. 

> I just want the formatter to respect if I put the “)” on the next line on purpose.

I can probably configure it to always preserve positions for parentheses - so that if you choose to put a closing parenthesis on a new line, it will keep it there, only fixing indentation. More generally, I think I may do a sweep of the current plugin settings to see if I can make it all a bit more lenient. If that succeeds, it also means that it won't really affect existing code, as the formatting rules won't have changed, but merely relaxed a bit.

> I’m a bit used to the lenient formatter in IntelliJ.

Yes, same (except, of course, I use the Eclipse IDE formatter).

The fundamental problem is not Eclipse vs IntelliJ - it's that we are now enforcing very strict formatting settings through the maven plugin, rather than just relying on individual developers to configure their environment properly and do their best. The upside is that we have very uniform code formatting, but of course the downside is that it leaves little room for leniency. If I can make the formatting rules for the plugin a bit less severe, it will make life easier for everyone I think.

**Comment by jeenbroekstra** [comment]
Unfortunately it turns out the maven formatter plugin we use is behind in terms of what the eclipse formatter can do - so this particular tweak is not something we can currently do. We'll need to wait until there's a new release of that plugin (or find some other way to handle this).

**Comment by hmottestad** [comment]
We can just leave this issue open for the time being then. I’ve added formatting escape around the code that I wanted to fix.

**Comment by jeenbroekstra** [comment]
> We can just leave this issue open for the time being then. I’ve added formatting escape around the code that I wanted to fix.

I've logged a ticket with the plugin project to see what can be done: https://github.com/revelc/formatter-maven-plugin/issues/343

**Comment by jeenbroekstra** [comment]
We've been nudged by the plugin developers that they are releasing a new version soon, and have been asked to test their current master branch version. I'll try and find time for this this week.
