### ISSUE TITLE
Support for sail config on Repository level

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2322]
Users who talk to the ShaclSail through a `HttpRepository` and `HttpRepositoryConnection` should be able to:
 - enable or disable validation in the ShaclSail
 - call revalidate() in the ShaclSailConnection (split out into new issue #2325)

**Comment by hmottestad** [comment]
@jeenbroekstra this is a use case that Ontotext has come with. Could you shed some light on how remote configuration is currently handled in RDF4J.

My natural instinct is to create a new class for `HttpShaclSail` and `HttpShaclSailConnection` that could be retrieved from the `HttpRepository` and `HttpRepositoryConnection` respectively. These would then expose the relevant methods to the user.

**Comment by jeenbroekstra** [comment]
How do people who work locally currently do this?

**Comment by jeenbroekstra** [comment]
What I'm getting at with that is that we should think about a generic mechanism to control such settings at the Repository API level, so that (either locally or remotely), people can control this without having to directly interact with the SAIL. 

Normally, remote configuration is handled by sending an RDF-serialized RepositoryConfig (with a SailImplConfig etc) through the RemoteRepositoryManager, but that mechanism is not really suitable for these kinds of "per-connection" or even "per-operation" config settings.

**Comment by hmottestad** [comment]
I personally get the sail from the repo and cast it to a ShaclSail. Same for the connection. When working locally that is.

The RemoteRepositoryManager would work for disabling and enabling validation, since this is a global setting.

For interacting with the connection I really like the casting approach:

```java
HttpRepositoryConnection connection ... ;
HttpShaclEnabledRepositoryConnection shaclConnection = connection.as(HttpShaclEnabledRepositoryConnection.class);

// revalidation
ValidationReport = shaclConnection.revalidate();

// custom transaction support
shaclConnection.begin(Validation.disabled);
....
shaclConnection.commit();
```

One thing I'm wondering about. Does the HttpRepositoryConnection support transactions fully. Essentially, do we have a POST /startTransaction endpoint?

**Comment by jeenbroekstra** [comment]
On my phone so brief, but I'm not a fan of solving this through inheritance. 

I'm thinking instead we add a new ConnectionSettings object that you can get/set on a RepositoryConnection.

**Comment by jeenbroekstra** [comment]
> One thing I'm wondering about. Does the HttpRepositoryConnection support transactions fully. Essentially, do we have a POST /startTransaction endpoint?

It does. Or rather: the RDF4JProtocolSession (which is used by the HTTPRepositoryConnection) does.

**Comment by jeenbroekstra** [comment]
> I personally get the sail from the repo and cast it to a ShaclSail. Same for the connection. When working locally that is.

We need a better mechanism for that. Users shouldn't need to interact with the Sail objects directly. 

Let's do some rough sketches, how about making something like this possible:

```
RepositoryConnection conn  = ...;
conn.getSettings().set(ShaclSettings.validate, false);  // disable validation
conn.begin();
...
```

The result of `RepositoryConnection.getSettings()` would be a ConnectionConfig object, similar to how we have a `ParserConfig` in Rio, which takes a `ConnectionSetting` object and a value (similar to how `ParserConfig` takes a `RioSetting` object and a value). Once we have this in place it shouldn't be hard to add a generic serialization mechanism so that we can transmit these settings over the REST api. 

If I understand the purpose of the `revalidate` method correctly, it is to kick off validation of the entire store without having to add new data (for example after you've added some data with validation disabled). If that is the case, I'm thinking that we could support this by having a generic `RepositoryConnection.refresh()` (and accompanying `SailConnection.refresh()`) that in case of the ShaclSail can interally call `revalidate`. The reason I want this generically solved is that it opens up other use cases (outside of SHACL validation) where internal components need to recompute things, and moreover it allows interaction with SHACL-enabled repositories without having to couple client code to specifics of the SHACL sail.

**Comment by hmottestad** [comment]
I think we should treat validation as a separate feature, like how we treat reasoning as a separate feature. Even if you don’t use a reasoner sail you still get the option to retrieve inferred triples. 

Refresh would be a good option for a lazy reasoner. 

Revalidate would be a good option for a lazy validator. 

But this still doesn’t handle my wish to add a transaction begin option without validation. Though I’m not having second thoughts about that :P

I like the settings approach for the repository. Would make it immutable so the user would have to call repo.setSettings(my settings); or something like that. Makes it easier to handle for the http repo. I think i will look into coding that.

**Comment by jeenbroekstra** [comment]
> I think we should treat validation as a separate feature, like how we treat reasoning as a separate feature. Even if you don’t use a reasoner sail you still get the option to retrieve inferred triples.

To be honest, in retrospect I would have preferred that we had solved that differently - it's regularly caused confusion in our users who think that by supplying `true` to that parameter they "turn on inferencing". 

> Refresh would be a good option for a lazy reasoner.
> 
> Revalidate would be a good option for a lazy validator.

I don't see why there should be a naming difference for this at the core API level - both operations signal a message to refresh the state of the store. But if you really think `revalidate` is better, we can facilitate this at the Repository API level by providing a Wrapper or a util class of some sort, e.g. a ValidatingRepository(Connection) which wraps a normal Repository(Connection) and has an additional `validate()` method that calls `refresh` on the base RepositoryConnection. 

> But this still doesn’t handle my wish to add a transaction begin option without validation. Though I’m having second thoughts about that :P

I suggest we treat that as a separate issue for now. One possibility is that we add an optional argument to the `begin` method that takes a ConnectionConfig object. Or, alternatively, and more flexibly, we don't actually change the begin method at the core API level, but let that same wrapper or util at the Repository API level take care of this for us.  

> I like the settings approach for the repository. Would make it immutable so the user would have to call repo.setSettings(my settings); or something like that. Makes it easier to handle for the http repo. I think i will look into coding that.

That'd be great. Keep in mind that making the config immutable will make it harder to manipulate on the fly. I do agree that `RepositoryConnection.getConfig()` should retrieve a copy of the current config, but it should still be possible to tweak the individual settings in that config, so that you can do one-line config tweaks like this:

     connection.setConfig(connection.getConfig().set(ShaclSettings.VALIDATE, false));

unless that is what you meant with making it immutable, in which case, great :)

**Comment by hmottestad** [comment]
The problem with `refresh()` is that it doesn't tell the underlying store anything about what it should be refreshing.

 - For the ElasticsearchStore it could signal an index level refresh. Maybe rebuild the statistics.
 - For the NativeStore it could signal a flush and maybe a recalculation of statistics (dunno if we have statistics for the NativeStore). It would also signal a compaction of the hashmap. Realignment of the values files. Or maybe re-indexing data into new trees if the user changes which indexes they want. Or maybe dropping all caches.
 - For any inferencer it would likely mean to remove all inferred triples and re-infer them.
 - For the memory store it could mean to flush to disk if a disk is specified. Or sort all the statement lists. Or maybe compact all lists to take up less memory. Or intern all strings.

Another issue is the `refresh()` would have to either not return anything. Or return an object that the user needs to cast. 

Essentially I feel that ´refresh()` is too fuzzy and it tries to solve a problem we don't have. The problem we have is the need for a user to interact with some specific feature of the underlying sail.

And for the immutable config. I meant an immutable config object. Calling  `connection.getConfig().set(ShaclSettings.VALIDATE, false)` would return a clone.

**Comment by jeenbroekstra** [comment]
> The problem with `refresh()` is that it doesn't tell the underlying store anything about what it should be refreshing.
> 
>     * For the ElasticsearchStore it could signal an index level refresh. Maybe rebuild the statistics.
> 
>     * For the NativeStore it could signal a flush and maybe a recalculation of statistics (dunno if we have statistics for the NativeStore). It would also signal a compaction of the hashmap. Realignment of the values files. Or maybe re-indexing data into new trees if the user changes which indexes they want. Or maybe dropping all caches.
> 
>     * For any inferencer it would likely mean to remove all inferred triples and re-infer them.
> 
>     * For the memory store it could mean to flush to disk if a disk is specified. Or sort all the statement lists. Or maybe compact all lists to take up less memory. Or intern all strings.
> 

That was actually precisely the point. 

> Another issue is the `refresh()` would have to either not return anything. Or return an object that the user needs to cast.

That's not a problem. At the sail level, we can return a generic Report interface (or even a List<Report> if we want to suport multiple sails in the stack each giving their own report). At the Repository API level, we can have code that inspects the lists of reports and fishes out the one that is fit for purpose (so e.g. a ValidatingRepository could fish out a ValidationReport).

But I appreciate now that all of this may be a bit YAGNI. I'm just trying to make sure we can keep the core SAIL and Repository interfaces as minimal and generic as possible. 

> Essentially I feel that ´refresh()` is too fuzzy and it tries to solve a problem we don't have. The problem we have is the need for a user to interact with some specific feature of the underlying sail.

Users _don't_ interact with specific features of an underlying Sail - at least not directly. A Sail is _hidden_. What a user wants is to make sure is that they get a report that tells them if anything in their repository violates the shape constraints. It's the Repository API's job to translate that high-level request into specific operations on the SAIL stack. 

All that being said, I think we can't avoid the fact that for validation, we will need _some_ sort of first-class citizenship in both the Repository and SAIL interfaces. The generic refresh idea might be nice but it's a bit overengineered for our immediate needs, I've come to agree. 

I will want it a _bit_ generalized/abstracted from the specifics of the ShaclSail implementation. Can we call it `validate()` instead - the semantics being "validate the current state of the connection and produce a report" or something along those lines. It will give us flexibility to in future maybe consider more sophisticated behavior (e.g. when used in a transaction it only validates the added data in the transaction, but when used outside it, it re-runs validation on the entire store - not saying that that is a good idea right now, just saying that _maybe_ we might want something like that). 

I suggest that we move the `ValidationReport` class out of the SHACL Sail package, and move it to the repository-api module so it is reusable both locally and remote. We can then add a method `RepositoryConnection.validate()` which returns an (optional) `ValidationReport`. At the SAIL level, we can add a `SailConneciton.validate()` which can return an iteration of statements. Default implementation will be a no-op, and we'll need to ensure the wrapper implementations all delegate it. 

Actually, perhaps slightly better would be to introduce new interfaces for the new method in both APIs: `ValidatingRepositoryConnection` and `ValidatingSailConnection`. We can then make sure that the relevant implementations implement those interfaces. Similar to how we have, for example, NotifyingRepositoryConnection and NotifyingSailConnection. 

> And for the immutable config. I meant an immutable config object. Calling `connection.getConfig().set(ShaclSettings.VALIDATE, false)` would return a clone.

I think we agree :) I guess I was just confused by using the term "immutable" in this context (as far as I can tell no object is actually made immutable, we are simply not giving direct access to modify the internal copy).

**Comment by jeenbroekstra** [comment]
I've split this out into two cards: this current card can focus on the config stuff, while a new issue (#2325) can focus on the new `validate()` API method.

**Comment by jeenbroekstra** [comment]
Relevant part of the REST API documentation: https://rdf4j.org/documentation/reference/rest-api/#repository-configuration

**Comment by hmottestad** [comment]
closing since this problem is solved with transaction settings
