### ISSUE TITLE
Support explicitly creating a ValidationReport on a Validation-enabled Repository 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2325]
Followup from #2322. As a user I want to call `validate()` on a repository connection so that I can retrieve a validation report that tells me the state of store / connection.

As discussed in #2322 we will support this as follows:

1. In the Sail API, we add  a new behavioral interface `ValidatingSailConnection` which has a method validate() returning a statement iterator. ShaclSail will implement this method doing actual validation, other SailConnection implementation will pass to the delegate or (if a base sail), return an empty result.
2. In the Repository API, we add a new behavioral interface `ValidatingRepositoryConnection` which has a method `validate()` returning a optional ValidationReport. Relevant RepositoryConnection implementations (e.g. SailRepositoryConnection) can implement this interface: if the underlying sailconnection is a ValidationSailConnection, retrieve the reporting statements and turn them into a ValidationReport object, otherwise return an empty optional.
3. To support communicating this new feature over HTTP, the RDF4J REST API will need to be extended with a new operation, at both client (RDF4JProtocolSession) and server (RepositoryStatementController / TransactionController) ends.

**Comment by jeenbroekstra** [comment]
Why was this closed? I'm a little lost on what problems you're solving under which tickets and PRs to be honest.

**Comment by hmottestad** [comment]
Because I don't think it's something we need to solve anymore. The design of the transaction settings allows us to force full validation on a transaction regardless of what it changes. So users should then catch the validation exception.

The only reason we introduced a revalidate() method was to allow users to bulk insert data with validation disabled and then later on run a full validation. When we have the transaction settings in place I will deprecate the revalidate method.
