### ISSUE TITLE
NTriples parser seems to fail on nt-syntax-bad-lang-01 

### ISSUE THREAD

**Issue by bblfish** [eclipse/rdf4j#2356]
Upgrading [banana-rdf](https://github.com/banana-rdf/banana-rdf) to the latest rdf4j 3.2.3  (see [PR 352](https://github.com/banana-rdf/banana-rdf/pull/352)) I noticed that the [nt-syntax-bad-lang-01](https://www.w3.org/2013/N-TriplesTests/nt-syntax-bad-lang-01.nt) from the test suite https://www.w3.org/2013/N-TriplesTests/ is failing. Ie the parser allows the `@1` language tag. 

I am fixing that PR, and that is the only bug left.

I will try to disable that test for the moment. But am opening this ticket to remind me to undo that if fixed.

**Comment by jeenbroekstra** [comment]
I can not reproduce this locally. The N-Triples parser fails as expected on that test case (in fact that entire test suite is part of our CI process). 

The only thing I can think of is that you have tweaked the default configuration of the parser. If `NTriplesParserSettings.FAIL_ON_INVALID_LINES` is set to `false` (the default is `true`), then the parser will silently ignore the problem. If in addition you have also set `BasicParserSettings.FAIL_ON_UNKNOWN_LANGUAGES`, the parser will log a warning about the unrecognized language but otherwise ignore it.

**Comment by bblfish** [comment]
Thanks for the help. I have been away from banana-rdf for a few years, and we just did a big upgrade from Sesame to the latest RDF4J. It was actually a problem with my  NTriplesParser in the test where it  creating RDF4J objects. Creating a broken RDF4J literal also threw a IllegalArgumentException, so one more exception than expected. 

The PR to fix it is here
https://github.com/banana-rdf/banana-rdf/pull/357/files#diff-79a250d046f1c76aaf5cb659fbf71b1cR525

But there's no problem on your side.
