### ISSUE TITLE
SHACL: datatype validation does not occur on the first insert after a fresh launch of RDF4J

### ISSUE THREAD

**Issue by rdstn** [eclipse/rdf4j#2385]
I'm seeing an odd edge case behaviour with SHACL on 3.3.0-M2. Given this SHACL schema snippet:

```
	sh:property [
		sh:path ont:int; 
		sh:datatype xsd:integer; 
	] .
```
Whenever I completely clean the SHACL repo (I'm running under Docker, so I drop the Docker container and delete all volumes) and start from scratch, the first time I insert data with the pattern:
`<ont:something> <ont:int> "I am a teapot!"`
No validation errors are reported, even though the data is non-compliant. 

Following this, SHACL works as expected. This does not re-occur on subsequent launches of RDF4J.

I've not tested this exhaustively, but the issue does not appear to be present for cardinality validation.

**Comment by hmottestad** [comment]
We definitely have tests that are supposed to cover that case. Are you able to reproduce it with just java code and the memory store? Or any chance you have some other simple way for me to reproduce it?

There are some performance optimizations that run on the initial commit that for this case will execute a sparql query against the underlying transaction instead of the traditional transactional validation approach.

**Comment by rdstn** [comment]
We changed the source on our end and can no longer reproduce the error. My hunch is that it was related to the following piece of odd SHACL that we no longer use:

`sh:datatype rdf:Resource ;`

I tested wtih the current version of the workbench, the server and the API and could not reproduce the error. I think the issue is safe to close.
