### ISSUE TITLE
Language subtags and wildcards in SHACL

### ISSUE THREAD

**Issue by rdstn** [eclipse/rdf4j#2452]
At the moment, the SHACL parser does not appear to consider subtags when using languageIn. Given the following SHACL:

```
ex:LanguageShape
	a sh:NodeShape ;
	sh:targetNode ex:LangTest;
	sh:property [
		sh:path ex:prefLabel ;
		sh:languageIn ( "en-*" "fr" ) ;
	] .
```

This should validate that the language of `ex:prefLabel` is tagged as either French, or one of the 10 possible English subtags. However, the following data is considered invalid:

```
ex:LangTest
    a ex:Language ;
    ex:prefLabel "Abra"@fr ;
    ex:prefLabel "cadabra"@en-GB ;
```

The reason is that wildcards are not used and tags are a rather simple 1:1 mapping:
```
Optional<String> language = ((Literal) t.getLine().get(1)).getLanguage();
return language.filter(languageIn::contains).isPresent();
```

A minor issue is that there's no validation on the inputs to SHACL, so it's possible to input a nonsensical language tag:
```
		sh:languageIn ( "Old McDonald had a farm!" ) ;
```

However, this one should be easy to resolve at the client level by switching from the `SimpleValueFactory` to a `ValidatingValueFactory`.

**Comment by jeenbroekstra** [comment]
@hmottestad  would you consider this an improvement, or a bug?

**Comment by hmottestad** [comment]
This is a bug. I've overlooked the definition which states "A list of basic language ranges as per [BCP47]".

**Comment by jeenbroekstra** [comment]
The `org.eclipse.rdf4j.rio.languages.BCP47LanguageHandler` class might be something we can reuse here.

**Comment by rdstn** [comment]
Do you think that the language handler would also help with the country tags in SHACL?

At the moment, if you insert data in the triplestore, for example, with `en-gb` as the language tag, this gets capitalized to `en-GB`. However, the same does not apply to the SHACL insertion - the constraint ends up as `en-gb`, lowercase, and we get validation errors.

**Comment by hmottestad** [comment]
I've been working on support for `sh:not` in the new SHACL implementation so I haven't looked at this. I just want to spend a bit more time with `sh:not`, since I can see that I'm very close and I know what the next step is.

Ill take a look at this issue here soon though, and also merge in this one: https://github.com/eclipse/rdf4j/pull/2459

**Comment by hmottestad** [comment]
This is a bit more complicated than I had initially thought.

From the BCP 47 spec:

Example range: `de-*-DE`
Example of tag that does **not** match: `de-x-DE`
Example of tag that does match: `de-DE-x-goethe`

**Comment by hmottestad** [comment]
Found this: https://docs.oracle.com/javase/8/docs/api/java/util/Locale.LanguageRange.html#LanguageRange-java.lang.String-

**Comment by hmottestad** [comment]
I'm asking Andy about how language tags are supposed to work for langMatch, which is the SPARQL filter that the SHACL languageIn constraint is defined by.

The current issue is that the langMatch filter in RDF4J doesn't support "en-*" since this type of language range is not allowed in the basic range. The range "en" will do pretty much the same thing though, with the only difference that it will match "en" as well as "en-GB" and so on.

**Comment by hmottestad** [comment]
This is fixed in so much that we follow the spec. I know the reference SHACL engine support things like "en-*" because Jena does, and we are having a discussion about doing something similar over here: https://github.com/eclipse/rdf4j/issues/2500
