### ISSUE TITLE
How to implement High availability with Rdf4j

### ISSUE THREAD

**Issue by xsfang** [eclipse/rdf4j#2788]
Thank you.

**Comment by jeenbroekstra** [comment]
Can you give some more context and/or clarify exactly what your'e after?

**Comment by barthanssens** [comment]
Well, it depends on the use case ... if it's just reading / querying data (not writing), one option could be to create a docker image with data in it, and add a load-balancer / failover proxy like HAProxy.

For read-write use cases, you might want to look into a commercial solution like OntoText GraphDB, or the open source Merck Halyard (based on Hadoop) which are both using RDF4J

**Comment by xsfang** [comment]
@jeenbroekstra, I am just trying RDF4j for study. 
@barthanssens, thank you. Could you give me more details on how to use docker image + load-balancer / failover proxy solution?

Thank you very much!

**Comment by xsfang** [comment]
I am trying to find high availability functions on Halyard. Could you possibly plearse give me any document link?

Thank you very much!
:)

**Comment by barthanssens** [comment]
Halyard is implemented on top of Hadoop, so the high availability depends on the Hadoop configuration. The Halyard documentation recommends to use Hortonworks HDP, so you probably want to consult the admin guide https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.0.6.0/bk_system-admin-guide/content/ch_hadoop-ha.html

(note that Halyard is using an older version of RDF4J)

----

Stardog is another commercial platform with HA-functions (https://docs.stardog.com/cluster/) which supports the RDF4J API (https://docs.stardog.com/developing/programming-with-stardog/java#using-rdf4j)

And there is also Amazon NeptuneDB (https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-sparql-rdf4j-console.html) which can also accessed via RDF4J

----

Yet another approach (which I'm using for a _read-only_ small website) is to embed the RDF4J memory store or native store into a standalone web application, add it to a docker container together with data, and deploy it on an openshift cloud environment (which can be set up to provide HA).

See https://github.com/belgif/vocab-belgif

The amount of data is actually very limited, and is simply loaded on start-up. It is not really designed for a massive amount of users, but it is "high available" in the sense that e.g. openshift can spin up a newer version and replace the older version when ready.

---

Something similar could be achieved with and putting e.g. HAProxy in HTTP mode in front of it (https://www.haproxy.com/documentation/aloha/12-5/traffic-management/lb-layer7/http-modes/), or another HA proxy

And/or use the docker images available for the RDF4J server and workbench (https://hub.docker.com/r/eclipse/rdf4j-workbench)

Please note that the RDF4J server itself was not designed for providing HA, and/or handling many billions of triples, so this setup may not be enough for covering the same use case as Halyard/GraphDB


It really depends on the use case ...

And again, this is for read-only applications (or when updates can easily be repeated on all dockers), because one RDF4J server does not replicate to / share updates with other servers.

**Comment by hmottestad** [comment]
Closing this since there has been no replies from @xsfang for over a week and HA isn't on our roadmap.
