### ISSUE TITLE
Blank node inlining breaks after sorting statements

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2830]
Try the following java code:

```java
		Model model = Rio.parse(new StringReader("[] <http://www.z.org#a> (<http://www.z.org#o> <http://www.z.org#z>) .") , RDFFormat.TURTLE);

		ArrayList<Statement> statements = new ArrayList<>(model);
		ValueComparator valueComparator = new ValueComparator();
		statements.sort(
			Comparator
				.comparing(Statement::getObject, valueComparator)
		);

		model = new LinkedHashModel(statements);

		WriterConfig writerConfig = new WriterConfig();
		writerConfig.set(BasicWriterSettings.INLINE_BLANK_NODES, true);

		Rio.write(model, System.out, RDFFormat.TURTLE, writerConfig);
```

Expected:
```
[] <http://www.z.org#a> (<http://www.z.org#o> <http://www.z.org#z>
```

Actual:
```
[] <http://www.z.org#a> [] .

[] <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> [] .

[] <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>;
  <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.z.org#z> .

[] <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.z.org#o> .
```

**Comment by hmottestad** [comment]
@jeenbroekstra you're the leading expert on the blank node inlining code, you want to take a look to see what is going on?

**Comment by hmottestad** [comment]
FYI, the use case here is part  the test suite for the ShaclSail. After checking if two models are isomorphic I like to sort them so that the pretty printed output is as similar for the two models as possible to easily spot the difference.

**Comment by jeenbroekstra** [comment]
The cause seems to be specific to the private `handleList` method. It seems to assume that the statements making up the RDF Collection are fed to it in the correct order (or rather, that the first statement it gets is the first `rdf:first` statement). This works when using natural ordering, but not when a custom comparator is added. 

I haven't looked in detail yet, will try and find some spare time later this week, but I suspect that a hardcoded filter to handle rdf:first predicates before others (somewhere around line 875 in TurtleWriter) might fix the issue.

**Comment by jeenbroekstra** [comment]
> FYI, the use case here is part the test suite for the ShaclSail. After checking if two models are isomorphic I like to sort them so that the pretty printed output is as similar for the two models as possible to easily spot the difference.

This uncovered a bug so that's good, but: if it's easy diffing of models you're after, why don't you just use a `TreeModel` rather than this convoluted custom sorting approach on a LinkedHashModel?

**Comment by jeenbroekstra** [comment]
Ok, so "later this week" was now :stuck_out_tongue: . PR up.
