### ISSUE TITLE
Isomorphism ignores datatypes and language tags

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2843]
I'm wondering if the following two models, one with an untyped number and the other with an xsd:long are supposed to be isomorphic.

```
@prefix ex: <http://example.com/ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rsx: <http://rdf4j.org/shacl-extensions#> .

ex:PersonShape sh:not [
      sh:not [
          sh:maxCount 3;
          sh:path ex:ssn
        ]
    ];
  sh:targetClass ex:Person .
```

```
@prefix ex: <http://example.com/ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rsx: <http://rdf4j.org/shacl-extensions#> .

ex:PersonShape sh:not [
      sh:not [
          sh:maxCount "3"^^xsd:long;
          sh:path ex:ssn
        ]
    ];
  sh:targetClass ex:Person .

```

**Comment by hmottestad** [comment]
@jeenbroekstra I'm wondering if this is a bug or if it is supposed to be like this?

**Comment by jeenbroekstra** [comment]
This is a bug in the new isomorphism algorithm, caused by the fact that for non-bnode values (IRIs and Literals) we rely on `Object.hashCode` to give us a unique hash identifier. That assumption is generally incorrect, and in particular in the case of Literals: `Literal.hashCode` uses only the lexical label, not the language tag or datatype (this is for performance reasons, see #665).

Fix is to calculate unique hashes for IRIs and Literals ourselves in the algorithm, instead of relying on Object.hashCode.

**Comment by jeenbroekstra** [comment]
Actually slight amendment: we don't rely on Object.hashCode, but what we do is using `.stringValue` to calculate the hash, which in the case of literals only gives the lexical value back. Different root cause but same sort of effect :)
