### ISSUE TITLE
Concurrent reads from SailConnection

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2874]
The ShaclSail uses concurrent reads from a single connection to be able to validate shapes in parallel. We should investigate if this could be an issue. 

Java collections generally state that even though they don't support concurrency, they generally allow concurrent reads. So it makes sense for our connections to support concurrent reads and long as writes+reads are synchronized. 

One place this could be an issue is the observed statements in the Changeset. 

Essentially we need to look for statefulness in the code that would be connected to read operations.

**Comment by jeenbroekstra** [comment]
This is not something we can fix generally, or even want to. We have no full control over what third party implementations do, which means that you cannot rely on this behavior in your ShaclSail, even _if_ you manage to fix it in the specific nativestore/memorystore sail implementations.

**Comment by hmottestad** [comment]
We could make it required behavior starting with 4.0.0. 

It's important for the performance of the ShaclSail. And it would be useful behavior for supporting parallel query evaluation in the future. HashJoin could benefit from that.

**Comment by jeenbroekstra** [comment]
> We could make it required behavior starting with 4.0.0.

Not something this fundamental to the architecture. Not without serious polling of sail/repository implementors and getting their approval. At the _very_ least you will have to solicit approval from vendors like Ontotext, Stardog, Blazegraph and others. 

> It's important for the performance of the ShaclSail.

That's unfortunate, but unless you can get buy-in from third parties on the idea, you'll just have to find another solution that fits within the semantics of the framework. 

I also still don't buy that it is necessary, by the way. If you want to read things in parallel threads, just open two connections.

**Comment by hmottestad** [comment]
Opening multiple connections is a bit problematic since they would all need to contain the same changes as the current transaction. 

And parallel validation is particularly useful for bulk validation. Currently I'm seeing a 3x speedup on my 4 core MacBook.

**Comment by hmottestad** [comment]
Btw. Updated the title to reflect that this is only needed for SailConnections and not RepositoryConnections.

**Comment by jeenbroekstra** [comment]
> Opening multiple connections is a bit problematic since they would all need to contain the same changes as the current transaction.

...and I assume that you cannot rely on using something like READ_UNCOMMITTED isolation because that is only a minimal guarantee on what _might_ happen, not a guarantee that you definitelly _will_ see all changes before they're committed. Correct?

> Btw. Updated the title to reflect that this is only needed for SailConnections and not RepositoryConnections.

That limits the impact somewhat, though we'd still need to solicit opinions from the likes of Ontotext, who I know do their own SAIL API implementation. It's a bit pointless to make this performance improvement only to then find out that the likes of GraphDB can no longer use the ShaclSail.

If you think it's worth it: put together a proposal of _exactly_ what you want to do, what that would mean for sail implementors, and what benefits we would get from it, and get opinions on it from, _at least_, Ontotext, (and hopefully more stakeholders), then this is something we can take forward. I'd also like us to put some thinking into what the consequences would be for implementations that don't update their sail to the new behavior.

**Comment by hmottestad** [comment]
I've been reading through the code a bit, and there is a decent amount of synchronization and locking in the code that already assumes concurrent read access. Mostly looking at SailSourceBranch and SailDataset. I originally thought that maybe Changeset would be a problem, since reading at level SERIALIZABLE would mean concurrent writes to "observed", but that is not the case since most of Changeset is synchronized.

**Comment by hmottestad** [comment]
I've started to engage Ontotext on Slack.

**Comment by jeenbroekstra** [comment]
Good to know. Just be aware that I don't think many third party Sail implementations inherit from SailSourceConnection. Most will inherit from AsbstractSailConnection only, or even just directly implement from the base interfaces, doing their own locking / concurrency handling.

**Comment by avataar** [comment]
I agree it should be possible to rely on concurrent read support and you have Ontotext's blessing on this. Instead of enforcing this as a general requirement for SailConnection we could have a marker interface, e.g. ConcurrentSailConnection. Then code that requires concurrency will require a ConcurrentSailConnection instance, thereby forcing vendors to implement it if they want the extra features. This is more or less the same approach as the existing NotifyingSailConnection.

**Comment by hmottestad** [comment]
That's a good idea. I'll make a branch with this and start working on some compliance tests.

**Comment by hmottestad** [comment]
I've given this a quick sketch and found an issue.

Say that we introduce a new `ConcurrentSailConnection`. Then our `ShaclSailConnection` constructor would look like this:

```
<T extends NotifyingSailConnection & ConcurrentSailConnection> ShaclSailConnection(ShaclSail sail, T connection, ... ) {
    ....
}
```

The issue becomes if we still want to support non-concurrent connections. Like this:

```
ShaclSailConnection(ShaclSail sail, NotifyingSailConnection connection, ... ) {
    ....
}
```

This confuses Java since both constructors have the same erasure. 

For the ShaclSail it would then be more useful with a method instead: `sailConnection.supportsConcurrentReads()`

**Comment by jeenbroekstra** [comment]
Wouldn't you just keep the constructor as it is now and only check if the supplied connection also implements ConcurrentSailConnection at the point where you need to know?

I'm a little wary of adding new methods to the root interface, this kind of behavioral thing has previously always been done with additional (sub)interfaces (like NotifyingSailConnection etc). There's a minimality principle I'd like to stick to as much as possible for the core interfaces.

Come to think of it: there might be other kinds of objects where we'd like to signal that it can be safely used for concurrent reads. Instead of a `ConcurrentSailConnection` should we perhaps introduce a more generic behavior interface `ThreadSafeReadable` or something like that?

**Comment by hmottestad** [comment]
Thanks for explaining Jeen. Makes more sense. Dunno why my head was making it so complicated. 

Using the interface for models would also make sense. The TreeModel doesn't support thread-safe reads, so signaling that would be really useful. 

How would we signal that a stacked sail supported multithreaded reads on the condition that the provided base sail also supported it? For instance for something like `
new ShaclSail(new ForwardChainingRdfsInferencer(new MemoryStore()))
`

**Comment by jeenbroekstra** [comment]
> How would we signal that a stacked sail supported multithreaded reads on the condition that the provided base sail also supported it?

The interface would still have (one or more) boolean methods to signal the kind of concurrency allowed I think, so you'd have something like:

```
if (conn instanceof ThreadSafetyAware) { // I keep coming up with different names for this interface....
    boolean concurrentReadsAllowed = ((ThreadSafetyAware)conn).supportsConcurrentRead();
   ....
}
```

We can let `SchemaCachingForwardChainingRdfsInferencer` implement the new interface and when `supportConcurrentRead()` is called it inspects its base sail, if that supports it, it returns true, otherwise false. 

Does that make sense? In my head it's straightforward but perhaps I'm overcomplicating things.

**Comment by hmottestad** [comment]
Ok. So interface with method. Makes sense. I'm living on rather few hours of sleep, so my head was completely fixed on it having to be an empty interface.
