### ISSUE TITLE
Add "distinct" query parameter to rdf4j sparql endpoint

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#319]
Issuing a construct query to an RDF4J repository can return a serialization e.g. rdf+xml, that includes dups. While it is fine not to dedup the direct result of a construct query, arguably its serialization should be to save space/bandwidth. Probably, RIO should be responsible for doing this, either the framework itself or the individual graph writers.

**Comment by jeenbroekstra** [comment]
The problem is that de-duplicating means keeping results in memory, which breaks the streaming character of the writers and make them less scalable - not to mention that the extra verification step of course lowers writer performance. The philosophy behind the writers has always been to be as lean as possible - and barring corner cases usually the duplication is not so much that you appreciably save bandwidth (especially when using gzip compression). 

However, if you want to filter out duplicates, there are several options you can currently already use: the simplest one is to use `QueryResults.distinctResults(GraphQueryResult)`, before sending the result to the Rio writer. Or you can first read the result into a `Model` object: since a `Model` is a `Set`, it automagically removes duplicate statements. 

So instead of making this the responsibility of the writer itself I'd suggest we document the available options for de-duplication, and if there are cases where we need something extra we introduce utility functions to allow users to optionally filter out duplicates.

**Comment by pulquero** [comment]
I was thinking maybe there should be a RIO setting to enable dedup (off by default). It would be a natural compliment to the pretty_print option.

I would also like to see a "distinct" query parameter option added to the sesame server to enable it. As a user, I don't want to have to write/hack code just to get a canonical RDF+XML output from the server.

**Comment by jeenbroekstra** [comment]
If the scenario you have in mind is an option in the RDF4J Server / Workbench, then that sounds very useful. But this can be easily implemented without adding a Rio setting. 

I'm reluctant to add a Rio setting, mainly because the current options are, in my view, good enough to solve most cases and adding more options just makes the API more cluttered. The situation is different with pretty-printing, where there is no viable other approach; it _has_ to be implemented inside the writer.
