### ISSUE TITLE
Thread leak on remove operations on HTTPRepository

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#3329]
### Current Behavior

Active thread counts steadily increases until VM resources are depleted.

### Expected Behavior

Active thread counts stays constant at about the number of local CPU cores.

### Steps To Reproduce

Execute the following code against a native RDF4J repository.

```java
public static void main(final String... args) {

	final Repository repository=new HTTPRepository("http://localhost:7200/repositories/work");

	repository.init();

	IntStream.range(0, 1024).forEach(value -> {

		try ( final RepositoryConnection connection=repository.getConnection() ) {

			connection.remove(RDF.NIL, RDF.VALUE, RDF.NIL);

		}

		System.out.printf("%d%n", Thread.activeCount());

	});

	repository.shutDown();
}
```

Locally testing against Ontotext GraphDB 9.9.0 (based on RDF4J 3.7.1).

### Version

3.6.2

### Anything else?

* only remove operations are affected: works as expected after replacing `.remove` with `.add`
* leaking threes are generated at `RDF4JProtocolSession:154` as `rdf4j-pingScheduler`

**Comment by knoan** [comment]
Executing code inside an explicit transaction won't change the observed behaviour.

**Comment by jeenbroekstra** [comment]
I can reproduce the observed behavior against a vanilla RDF4J Server as well.

Cause appears to be in RDF4JProtocolSession.close, which neglects to the shutdown the ping scheduler.

**Comment by jeenbroekstra** [comment]
The reason this occurs on remove operations but not on add is that for add operations we have a shortcut check to see if the operation is part of a larger transaction, and if not, just do the add directly instead of opening a new transaction for it. For some reason, that same shortcut has been commented out for the remove operation. I'll take a closer look at why that is the case.
