### ISSUE TITLE
XML-based parsers should not load external DTDs by default 

### ISSUE THREAD

**Issue by lewismc** [eclipse/rdf4j#3347]
### Problem description

We recently received a improvement request for Any23 to [optionally disable remote HTTP connections when resolving XML entities](https://issues.apache.org/jira/browse/ANY23-504). Any23 utilizes rdf4j 3.1.2. The stack trace provided by the reporter indicates that `org.eclipse.rdf4j.rio.trix.TriXParser` parsing can lead to a hung thread (for about two minutes) with an open HTTP connection.
I am writing here to see if this is something we can configure in RDF4J or whether we need to go deeper into Xerces or even the SUN HttpClient. I am looking for some guidance.

### Preferred solution

The [test file](https://github.com/apache/nutch/blob/master/src/plugin/any23/sample/BBC_News_Scotland.html) is available for anyone interested in trying to reproduce this issue. I am looking for some guidance on where this configuration would actually be implemented. Thanks for any suggestions. 

### Are you interested in contributing a solution yourself?

Yes

### Alternatives you've considered

Nothing yet. Apart from studying the `org.eclipse.rdf4j.rio.trix.TriXParser` source code this is the first port of call. Thanks for anyone who is interested in this issue.

**Comment by jeenbroekstra** [comment]
I am not entirely sure what is going on here - the RDF4J XML parsers (including the TriX parser) are configured to disallow processing external entities by default (since they're a security risk). See GH-1056. So this may be an edge case of some sort that we haven't covered, or perhaps Any23 has tweaked the parser configuration to "re-allow" external entities somehow?

The RDF4J parser tweak this, by the way, by setting the appropriate feature flags on the JAXP SAXAdapter. Here's a good overview of the various settings: https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXP_DocumentBuilderFactory.2C_SAXParserFactory_and_DOM4J

The attached test file is an html file by the way, which makes it a bit tricky for me to trace what is going on - presumably Any23 extracts some RDF content from this file which it then passes on to the TriXParser to process? Is it possible for you to show what the content that the TriXParser tries to parse looks like?

**Comment by lewismc** [comment]
Thanks for taking a look @jeenbroekstra

> or perhaps Any23 has tweaked the parser configuration to "re-allow" external entities somehow?

I studied the Any23 source code and **_CANNOT_** find any evidence of that being the case.

> presumably Any23 extracts some RDF content from this file which it then passes on to the TriXParser to process?

Yes

> Is it possible for you to show what the content that the TriXParser tries to parse looks like?

Yes, I can debug the code and provide that.

**Comment by lewismc** [comment]
Hi @jeenbroekstra [I made slight progress](https://github.com/apache/any23/pull/205). I wanted to update... I am working on this one :)

**Comment by jeenbroekstra** [comment]
> For example, when I attempt to parse the [test file](https://github.com/apache/nutch/blob/master/src/plugin/any23/sample/BBC_News_Scotland.html) I get the following partial stack trace
> 
> ```
> FATAL: 	'org.eclipse.rdf4j.rio.RDFParseException: The attribute name must be specified in the attribute-list declaration for element "charset". [line 181, column 45]
> 	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:333)
> 	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:724)
> 	at org.eclipse.rdf4j.rio.trix.TriXParser.reportFatalError(TriXParser.java:253)
> 	at org.eclipse.rdf4j.rio.trix.TriXParser.fatalError(TriXParser.java:419)
> 	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
> 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
> 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
> 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
> 	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanAttlistDecl(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
> 	at org.apa...' 	(-1,-1)
> ```
> 
> Thanks for any help in allowing me to better understand this.

That's roughly what I would expect to happen. The test file is an HTML file, not a TriX data file. The TriXParser makes an attempt to parse it as TriX format (which it can do to some extent, given that both HTML and TriX  are XML-based formats) but quickly fails because it doesn't encounter any of the expected elements and attributes.

**Comment by lewismc** [comment]
Hi @jeenbroekstra based on your input above, I [created a more suitable unit test](https://github.com/apache/any23/pull/205/files) which DOESN'T fix a bug neither does it verify the presence of a bug. Instead it demonstrates that the TriXParser should NOT be called when processing the test file BBC_News_Scotland.html. I have yet to figure out the root of why the TriXParser was activated whilst processing the sample document... I'll keep this issue open and report back when I/we figure that out.

**Comment by lewismc** [comment]
Thanks for providing the clarity :)

**Comment by lewismc** [comment]
@jeenbroekstra excellent!
Which version of rdf4j can wwe expect to see this ship in?
Thank you

**Comment by jeenbroekstra** [comment]
It's scheduled for 3.7.4, which we will likely release in a week or so.
