### ISSUE TITLE
FilterIterator mentions a work around, but when removed all tests are green

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#3601]
In the code of [FilterIterator](https://github.com/eclipse/rdf4j/blob/7efec1de9d2425ca61fddb30f0bfd0391935a5ef/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/FilterIterator.java) there is a FIXME comment.

> // FIXME J1 scopeBindingNames should include bindings from superquery if the filter
			// is part of a subquery. This is a workaround: we should fix the settings of scopeBindingNames,
			// rather than skipping the limiting of bindings.

If this work around is removed all tests pass and performance for some of my queries on a custom graph store speed up by a good 10% or so. The difference in performance is just to removing the making a new QueryBindingSet and retaining just the right variables.

Would anyone of us remember what the workarround is about. I suspect SERQL related due to the mention of

> the depth-first evaluation

@jeenbroekstra do you remember by chance ?

**Comment by jeenbroekstra** [comment]
Gosh this is old (back when I was young and cool and used "J1" as my handle). 

I don't fully remember what this is about and if it pertains to SeRQL only but the gist of it is that for a Filter clause that is in a subquery, we needed a workaround to make sure variables from the outer query are not removed by this step. I think we may have fixed that in some other place since then (e.g. by making sure that the Filter object itself actually has the correct binding names, including the ones from the outer query, set) - we've certainly done a lot of work on variable scope handling since Sesame became RDF4J, so you may be right that this clutch is no longer necessary. But it might be good to eyeball the tests we have and double-check that this kind of scenario is covered.
