### ISSUE TITLE
Improper IRI handling format

### ISSUE THREAD

**Issue by alw-iwu** [eclipse/rdf4j#3611]
### Current Behavior

When creating an Iri by calling
`Values.iri("http://opcfoundation.org/UA/Machinery", "6006").toString()` (please note that there is no trailing separator in the namespace) returns a String `"http://opcfoundation.org/UA/Machinery6006"`. There should be a convention to add the local Identifier as a segment or a fragment. Just concatenating it to the namespace seems wrong. I believe this is where the issue originates:

https://github.com/eclipse/rdf4j/blob/a1c5f8eca8b943026bee0cdd39ce869f285f5211/core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractIRI.java#L27

### Expected Behavior

`Values.iri("http://opcfoundation.org/UA/Machinery", "6006").toString().equals("http://opcfoundation.org/UA/Machinery/6006")`

### Steps To Reproduce

`assertTrue(Values.iri("http://opcfoundation.org/UA/Machinery", "6006").toString().equals("http://opcfoundation.org/UA/Machinery/6006")` and `assertTrue(Values.iri("http://opcfoundation.org/UA/Machinery", "6006").toString().equals("http://opcfoundation.org/UA/Machinery#6006")` will fail.

### Version

3.7.4

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by kenwenzel** [comment]
RDF4J does not try to be smart and expects that you already pass a valid namespace ending in `/`, `#` or `:` to the `Values.iri` function.

There is also a check at this point:
https://github.com/eclipse/rdf4j/blob/a1c5f8eca8b943026bee0cdd39ce869f285f5211/core/model/src/main/java/org/eclipse/rdf4j/model/impl/ValidatingValueFactory.java#L79

If this check fails then an IRI will be created but no further validations are executed.

BTW, I would expect that the call `Values.iri("http://opcfoundation.org/UA/Machinery", "6006")` produces `http://opcfoundation.org/UA/Machinery#6006` because there is no empty last segment in the namespace IRI
while `Values.iri("http://opcfoundation.org/UA/Machinery/", "6006")` could be combined to `http://opcfoundation.org/UA/Machinery/6006`.
What dou you think?

**Comment by jeenbroekstra** [comment]
This is by design, and strictly speaking the correct behavior. It follows the same rules as, for example, SPARQL does for determining the full IRI given a prefixed name (see https://www.w3.org/TR/sparql11-query/#prefNames ): simple concatenation. It's not explicitly stated in the docs for `Values#IRI`, but  it's also how the javadoc for `ValueFactory#createIRI` specifies it, see https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/model/ValueFactory.html#createIRI-java.lang.String-java.lang.String- :

> Calling this method is funtionally equivalent to calling createIRI(namespace+localName), [...]

**Comment by jeenbroekstra** [comment]
Also: there is no general rule that a namespace and local name _must_ be separated by a separate character such as '/' or '#' - that is a convention only. But strictly speaking a namespace is simply a common substring that many different IRIs can begin with. As long as the end result is a valid IRI, it's fine.
