### ISSUE TITLE
Backwards compatibility for RDF4JException and IsolationLevel(s)

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3742]
For 4.0.0 we have moved some common classes and interfaces into their own maven modules and their own packages.

This breaks pretty much all code the uses the old classes and interfaces, both for those extending or integrating with RDF4J and for regular users who uses RDF4J in their projects.

Also makes it that much hard for our users when they copy paste some code from older tutorials or examples and get a compile error due to a wrong package name.

I've previously complained that Elasticsearch changes up their packages without deprecation, but they have lowered the bar to a whole new level by releasing their changes in minor releases [[1](https://github.com/elastic/elasticsearch/issues/83980)].

It would be nice to bridge the gap in some way to allow old code to continue to work, while still moving to the new maven modules and packages. I'm not sure how exactly.

**Comment by hmottestad** [comment]
@jeenbroekstra I believe you were the one to change package names so I'm wondering what you think about my idea?

**Comment by jeenbroekstra** [comment]
For what it's worth I agree that it would have been better to have these old package names deprecated a couple of releases ago. 
 
However, I tend to think of package name changes like these as simple to fix in client code. Most IDEs have automatic import fixing tools available, you run it once over your project and your code is up to date again. 

The only thing I can think of that we could differently is to add old (deprecated) versions of the classes back in, so that code that uses those old package names continue to compile. However, this has several downsides as well:

-  if we add `org.eclipse.rdf4j.RDF4JException` as a (deprecated) subclass of the new `org.eclipse.rdf4j.common.exception.RDF4JException`, imports in existing code will continue to work, but any place where the code tries to `catch` this exception will fail - because the thrown exceptions will not be an instance of the deprecated type.

- if we try to fix that by adding `org.eclipse.rdf4j.RDF4JException` as  (deprecated) _superclass_ of the new class, we introduce a new dependency in the new class (a subclass relation), which we can't remove without another major release upgrade (because removing a class' superclass is a binary incompatible change). 

- regardless of which way around we add it, we would have two classes called RDF4JException in the code base, which makes usage more difficult as you'd have to choose which one to import every time you reference it in your code.

For those reasons I previously didn't go with this. My view is that as this is a major release, there's likely to be some other changes to existing client code anyway, and this particular change is not hard to fix quickly (in Eclipse, you'd hit Ctrl+Shift+O and you're done).

**Comment by aschwarte10** [comment]
To give this additional input: we have also used `RDF4JException` in quite some places in our application, and it was a trivial migration to the new package name (which I am perfectly fine to accept for a major release). In practice there are typically more different things to migrate in major releases - I think migration of RDF4J to the major release is specifically easy.

My personal vote would be to keep as it is currently defined. I do not see need for backwards compatibility here (especially as the upgrade steps are clearly documented)
