### ISSUE TITLE
Document step-by-step procedure for creating docker images and publishing them as part of release

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3768]
The process to create docker images for different architectures and to publish them to dockerhub as part of the release process is poorly documented. As a result we tend to forget to do this.

- [ ] the build script in src/main/dist/docker currently fails 
- [ ] there are no clear instructions on how to build images for both amd and arm architectures
- [ ] there are no clear instructions on how to set both version tag and 'latest' tag and publish the images to dockerhub
- [ ] there should be a reminder as part of the release process/script somewhere to take care of this

**Comment by barthanssens** [comment]
Yeah, I'll have to update and improve the outdated docs on https://rdf4j.org/documentation/developer/releases/#optional-publishing-docker-images

**Comment by jeenbroekstra** [comment]
Oh, I hadn't even seen that! I was looking at the Readme.dev in `assembly/src/dist/docker`.  We should perhaps remove that or at least link them.

**Comment by barthanssens** [comment]
Modern approach to do multi-arch builds: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide

**Comment by barthanssens** [comment]
So instead of separate tags per architecture, this can "now"  (well, since quite a while) be handled automatically by docker / hub.docker itself.

```
docker buildx build --platform=linux/amd64,linux/arm64 .
```

What also can be handled in docker (instead of a shell script) is building the project in a "first stage" (either do a complete build via mvn, or just download the zip from the rdf4j website) , then copying the result to the second stage using `COPY --from`

**Comment by barthanssens** [comment]
For automation, this action might be useful: https://github.com/docker/build-push-action

**Comment by barthanssens** [comment]
I think this one can be closed, see also #4243
