### ISSUE TITLE
HTTPRepositoryConnection.prepareGraphQuery() fails to throw IllegalArgumentException as documented in RepositoryConnection

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#420]
(Migrated from https://openrdf.atlassian.net/browse/SES-1932)

In SES-1931, a developer was confused by an exception later in execution when they provided a tuple query text to {{HTTPRepositoryConnection.prepareGraphQuery(...)}}. The {{RepositoryConnection.prepareGraphQuery(...)}} javadoc states that an {{IllegalArgumentException}} will be thrown for malformed queries. Some client-side parsing, if only to validate the query text, should happen so that the code fails fast as expected.

**Comment by barthanssens** [comment]
related to #399 ?

**Comment by jeenbroekstra** [comment]
@barthanssens not really, in this case. The situation here is that queries do not get parsed/validated at the client side in the HTTPconnection - it just sends the unparsed query string to the server when evaluate() is called, and then the server parses it - so from the client perspective the error happens on execute rather than parse. 

The issue you link to is, in a way, the same sort of thing, but it happens only for specific kinds of updates (namely INSERT DATA updates), and happens regardless of whether you are working over HTTP or with a local store. The cause in this case is that these updates are not pushed through the query parser but instead are passed on, at execution time, to a modified Turtle parser instead.
