### ISSUE TITLE
Remove Iteration interface

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#4359]
Related to #3907

Remove the Iteration interface and migrate to the CloseableIteration interface.

**Comment by kenwenzel** [comment]
@hmottestad I've noticed that `CloseableIteration` is marked as deprecated since 4.1.0. That leads to many warnings in the IDE. Is this due to the discussion if the interface should be kept at all or eventually replaced by an interface directly extending `Iterator`?

KOMMA does also just extend the iterator interface (borrowed from Jena):
https://github.com/komma/komma/blob/master/bundles/core/net.enilink.commons.iterator/src/main/java/net/enilink/commons/iterator/IExtendedIterator.java

**Comment by hmottestad** [comment]
@abrokenjester and I were considering removing the support for checked exceptions (as java generics) and that wouldn't make it backwards compatible. If we are doing that we might as well extend Iterator too.

**Comment by hmottestad** [comment]
### Develop
```
Benchmark                                                     Mode  Cnt     Score    Error  Units
QueryBenchmark.complexQuery                                   avgt    5     1.492 ±  0.032  ms/op
QueryBenchmark.different_datasets_with_similar_distributions  avgt    5     0.767 ±  0.021  ms/op
QueryBenchmark.groupByQuery                                   avgt    5     0.966 ±  0.040  ms/op
QueryBenchmark.long_chain                                     avgt    5   260.424 ±  8.599  ms/op
QueryBenchmark.lots_of_optional                               avgt    5    54.358 ±  0.439  ms/op
QueryBenchmark.minus                                          avgt    5  2350.765 ± 16.433  ms/op
QueryBenchmark.nested_optionals                               avgt    5    74.068 ±  0.110  ms/op
QueryBenchmark.pathExpressionQuery1                           avgt    5     8.003 ±  0.123  ms/op
QueryBenchmark.pathExpressionQuery2                           avgt    5     1.116 ±  0.033  ms/op
QueryBenchmark.query_distinct_predicates                      avgt    5    73.386 ±  0.367  ms/op
QueryBenchmark.simple_filter_not                              avgt    5     3.237 ±  0.061  ms/op
```
