### ISSUE TITLE
JSONLD context url not available anymore

### ISSUE THREAD

**Issue by jjkoehorst** [eclipse/rdf4j#4410]
### Current Behavior

I am obtaining JSONLD documents from a remote resource and it has the context 

`{"@context":["http://schema.org",{`

with the following code:

```
Model model = Rio.parse(new FileInputStream(destination), "", RDFFormat.JSONLD);
```

However this address now points to a normal webpage. I am able to load the JSON-LD files into triple stores but I am unable to process it with RDF4J as it throws a

`Caused by: com.github.jsonldjava.core.JsonLdError: loading remote context failed: http://schema.org`

Is there a way to get around this?

### Expected Behavior

Have an option available to bypass the context

### Steps To Reproduce

1. Any json ld file with a context that does not resolve.

### Version

4.2.2

### Are you interested in contributing a solution yourself?

None

**Comment by jjkoehorst** [comment]
I also tried:

```
            System.setProperty("com.github.jsonldjava.disallowRemoteContextLoading", "true");
            System.setProperty(DocumentLoader.DISALLOW_REMOTE_CONTEXT_LOADING, "true");
            Repository repo = new SailRepository(new MemoryStore());
            repo.getConnection().add(destination);
```

But then it will not continue as it is not allowed to fetch the remote context...?

`Caused by: com.github.jsonldjava.core.JsonLdError: loading remote context failed: Remote context loading has been disallowed (url was http://schema.org)`

**Comment by abrokenjester** [comment]
@jjkoehorst I'm afraid this is a problem with how the underlying jsonld-java parser works. The basic issue is really that a remote context establishes a mapping from shorthand terms to full IRIs in the document. If that mapping cannot be retrieved (for example because the document is no longer there), the parser fails because it won't know how to turn the shorthand terms into IRIs. I am not immediately aware of any easy way around this.

There are some options that involve manually configuring/overriding the default DocumentLoader behavior and/or manually injecting a context definition for the unavailalbe file into its internal cache. See https://github.com/jsonld-java/jsonld-java#loading-contexts-from-a-string .
