### ISSUE TITLE
SHACL - sh:pattern fails when double quotes are present (") in the pattern

### ISSUE THREAD

**Issue by Borislav-Bonev-Ontotext** [eclipse/rdf4j#4523]
### Current Behavior

If a sh:pattern node contains a double quotes (") the generated SPARQL query from the `PatternConstraintComponent` fails to parse.

### Expected Behavior

To be able the validate a literal that contains a double quotes

### Steps To Reproduce

Try to insert the following shape:

```
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vocsh: <http://example.org/shape/>
PREFIX ont: <http://example.com/ontology#>
INSERT DATA {
    GRAPH <http://rdf4j.org/schema/rdf4j#SHACLShapeGraph> {
        vocsh:Obj a sh:NodeShape ;
                  sh:targetNode <urn:test> ;
                  sh:property [ sh:path ont:weirdPatternTest ;  
                                sh:datatype xsd:string ;
                                sh:pattern "aaa\"bbb" 
                                # sh:pattern "aaa\\\"bbb" does not work as well or any odd number of escapes
        ] .
    }
}
```

### Version

4.2.2

### Are you interested in contributing a solution yourself?

Yes

**Comment by VladimirAlexiev** [comment]
@hmottestad We have a [related issue](https://ontotext.atlassian.net/browse/PLATFORM-4902): 
newline, linefeed, quote are escaped using `\`, but backslash is not escaped.
It's probably a bug within our platform, but I thought I'll mention it.

Both of these are invalid because `\w` is not a valid C/Java string escape. The backslash needs to be doubled: `\\`
```
sh:pattern "^https://example.org/agent/[\w_]+$"
regex(?url, "^https://example.org/agent/[\w_]+$")
```
