### ISSUE TITLE
Allow storage of Language country code in upper case

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#478]
(Migrated from https://openrdf.atlassian.net/browse/SES-1659)

The LiteralImpl class in Sesame's model currently normalizes all language tags to lower case before passing them on to the rest of Sesame. This is strictly speaking according to the spec, as the RDF Concepts & Abstract syntax recommendation states that language tags should be normalized to lower case. 

However, the issue reporter has stated a need for being allowed to store language tags 'as-is', that is, without Sesame normalizing them.

**Comment by jeenbroekstra** [comment]
@ansell given the discussion we are currently having at #665: isn't this already currently implemented? Clearly `SimpleLiteral` itself doesn't normalize.

**Comment by ansell** [comment]
Yes, this is already implemented, the change was a removal of the explicit lowercasing in SimpleLiteral/LiteralImpl in Sesame-4. Not sure why the Jira ticket wasn't closed with a release version of 4.0.

2.8 behaviour:

https://bitbucket.org/openrdf/sesame/src/aa292b3bee427c1a549b89a099a58d7edbe22d5a/core/model/src/main/java/org/openrdf/model/impl/LiteralImpl.java?at=2.8.x&fileviewer=file-view-default#LiteralImpl.java-112

4.0 behaviour:

https://bitbucket.org/openrdf/sesame/src/dbf38a8928c7f68edde798e6c4d3943be6a4c7b5/core/model/src/main/java/org/openrdf/model/impl/SimpleLiteral.java?at=4.0.x&fileviewer=file-view-default#SimpleLiteral.java-94

Lowercasing is (and has been since Sesame-2.7 I think) still available as a parser setting, BasicParserSettings.NORMALIZE_LANGUAGE_TAGS, which is not set to enabled by default. Its implementation is in the RFC3066LanguageHandler.normalizeLanguage method. If someone wanted the old behaviour they should be able to do it just by switching that parser setting on.
