### ISSUE TITLE
Query parser should report error when BIND is used with a variable that appears in the preceeding BGP

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#489]
(Migrated from https://openrdf.atlassian.net/browse/SES-1098)

See http://www.w3.org/TR/sparql11-query/#bind "Use of BIND ends the preceding basic graph pattern and the variable introduced by the BIND clause must not have been used in the immediate preceding basic graph pattern or property path expression." The query parser should detect if the variable has been used and if so, generate an error.

**Comment by barthanssens** [comment]
Seems to be fixed since Sesame 2.7.x (https://github.com/ansell/openrdf-sesame/commit/9ed322edee4547da0df1cc931959dca7bc7df573)

Tested "SELECT * WHERE { ?s ?p ?o . BIND (?p AS ?o) } in RDF4J 2.2 and got this exception, so it works as expected
"Exception in thread "main" org.eclipse.rdf4j.query.MalformedQueryException: BIND clause alias 'o' was previously used"
