### ISSUE TITLE
handle new logback based logging in RDF4J Console

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#544]
(Migrated from https://openrdf.atlassian.net/browse/SES-568)

The aduna application base switched from log4j to logback for logging. The Console needs to be modified accordingly, most notably the "set log" command.

**Comment by ansell** [comment]
Is this still an issue? I thought that we had switched to SLF4J-API for libraries and Logback for applications (console/workbench) already but I haven't verified that.

**Comment by josephw** [comment]
The `set log` command [suggested by `PrintHelp`](https://github.com/eclipse/rdf4j/blob/e42f4eebc55bd8ac2245cd4883b2f4704bfa4880/core/console/src/main/java/org/eclipse/rdf4j/console/PrintHelp.java#L74) doesn't work ("`unknown parameter: log`") since [SES-750](https://github.com/eclipse/rdf4j/commit/3349b45474d531cd1b483ca5fd5da2f2ed9270f1#diff-de6b8752185c42821ad34923dbeec7cbL1656).
