### ISSUE TITLE
Allow arbitrary SAX ContentHandler's to be used with RDFXMLWriter

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#546]
(Migrated from https://openrdf.atlassian.net/browse/SES-534)

Instead of writing directly to a java.io.Writer, RDFXMLWriter could write to a org.xml.sax.ContentHandler to allow arbitrary SAX ContentHandlers to be used. The current behaviour can be implemented by using info.aduna.xml.SAXWriter as the default content handler.

**Comment by ansell** [comment]
I don't think this is viable in the general case. We don't want to support yet another layer inside of the RDF/XML parser that we are planning to basically deprecate by changing its q-value in requests to make it less visible than it already is.

We already support custom XMLReader implementations, which are viable because they have performance differences, but the SAX ContentHandler doesn't have any performance characteristics, and may give spurious error messages that we would otherwise not have to deal with in bug reports.

**Comment by barthanssens** [comment]
So is this still a useful feature, or should it be considered to be a "wontfix" ?

**Comment by jeenbroekstra** [comment]
This is a very old ticket.  Happy to close it.
