### ISSUE TITLE
NativeStore should remove stale RDF values

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#550]
(Migrated from https://openrdf.atlassian.net/browse/SES-512)

Currently, the NativeStore doesn't not "garbage collect" values that are no longer referenced by statements. As a results, the values.hash, values.id, values.dat files can only grow over time. This is problematic in situations where the stored data changes very often.

**Comment by ansell** [comment]
Supporting this during the shutdown method while there is a full write lock and no outstanding connections should be a small/medium size task if the delete and squash primitives are already supported, otherwise it may be a large task. That is assuming this report from 2008 is still current and the GC functionality hasn't already been added.
