### ISSUE TITLE
MemValueFactory should intern IRI namespace strings during creation

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#558]
(Migrated from https://openrdf.atlassian.net/browse/SES-340)

Most of the time the namespace of a uri will exist as a static final in a class some where. In RDF(S) and OWL this exists in the vocabulary classes. During URI construction the namespace is obtained from a substring and shared with future URIs. MemValueFactory should share the exact namespace String with the system's intern String and not keep a second copy of every namespace in memory. This will eliminate some redundant namespace memory usage. Replace this: String sharedNamespace = _namespaceRegistry.get(namespace); With this: String sharedNamespace = namespace.intern();

**Comment by ansell** [comment]
The only references to intern that I can find in the current code are for language tags in RDFParserHelper and RFC3066LanguageHandler

Given we have Java-7 as our earliest supported version now (ie, where Oracle decided to start storing String.intern values on the Heap, not PermGen), String.intern should be safe to use in both major versions for namespace IRIs that are a much larger set than the language tags which form a very small set comparatively.

**Comment by barthanssens** [comment]
One corner case perhaps: what happens when there are a lot of different namespaces ?

I assume the method isn't only called when creating a predicate IRI, but also when creating subject IRI's, so I guess there could be a n impact if there are a lot of different subject namespaces ?

Which could happen when using the "BBC notation" (for the lack of a better term): the BBC publishes a lot of RDF metadata, using IRIs combining both the "slash" and "hash" notation (e.g.  newsfeed on http://www.bbc.co.uk/nature/collections/p01btg6w.rdf with IDs like `http://www.bbc.co.uk/programmes/p01f9y2w#programme`, `http://www.bbc.co.uk/programmes/p01f9nyx#programme` ...)

The benefit is that this style avoids an HTTP redirect while still making a distinction between the URL of the web page and the identifier.
Drawback: getNamespace will return a different namespace for every programme, because the IRI will be split on the '#'-character ...

```
public synchronized MemIRI getOrCreateMemURI(IRI uri) {
		MemIRI memURI = getMemURI(uri);
		if (memURI == null) {
			// Namespace strings are relatively large objects and are shared between uris
			String namespace = uri.getNamespace();
                        String sharedNamespace = namespaceRegistry.get(namespace);
			if (sharedNamespace == null) {
				// New namespace, add it to the registry
                               namespaceRegistry.add(namespace);
```

**Comment by ansell** [comment]
Java 7+ allocates interned Strings on the heap, and they are eligible for garbage collection when there are no more accessible references to them from user threads. This should result in a reduction in the total memory footprint, because the namespace string will be a single String object in memory that will be reused for all of the IRIs.
