### ISSUE TITLE
Lucene config template requires unused property

### ISSUE THREAD

**Issue by edwardsph** [eclipse/rdf4j#593]
Tested on RDF4J 1.0.1.
If you create a template without defining **indexDir** defined then you can't create a repository but the property has no effect on where indexes are stored. It appears that is now controlled by **lucenedir**.

**Comment by jeenbroekstra** [comment]
I'm not entirely sure I understand. What exactly do you mean when you say "creating a template" - are you trying to define your own template-file for instantiating a lucene-based repository (presumably for use in the Console)? And _why_ can't you create a repository without defining indexDir? What I mean is: what happens if you try, and which part of RDF4J "complains" about the missing indexdir?
