### ISSUE TITLE
Add documentation for GeoSPARQL functionality 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#605]
There is currently no documentation for the GeoSPARQL functionality, at all. This needs to change. We need documentation that at least explains:
1. that we support (part of) GeoSPARQL;
2. what parts are (and aren't) supported;
3. some simple examples on how to use it;
4. pointers on how to enable/configure GeoSPARQL support in RDF4J

**Comment by jinjin304616** [comment]
Hi, any document or example about how to use GeoSparql functions so far? Desperately need to know how it can work.

**Comment by jeenbroekstra** [comment]
@pulquero can you help me out with this? I'm a virtual newbie to GeoSPARQL myself, but if you can provide some example data and some simple queries that demonstrate what GeoSPARQL is all about I can probably write some basic getting started documentation around that.

**Comment by pulquero** [comment]
The definitive reference is here: https://portal.opengeospatial.org/files/?artifact_id=47664 , in particular, section 8.7. The are two parts to the GeoSPARQL support in rdf4j.

1) a bunch of functions. Add the jar to the classpath and they should be available. By default, there is basic support for WKT points. e.g. geof:distance("POINT (48.8582 2.2945)"^^wkt:wktLiteral, "POINT (48.8738 2.2950)"^^wkt:wktLiteral, <http://www.opengis.net/def/uom/OGC/1.0/metre>). To support more advanced shapes, a custom SpatialSupport impl can be provided. JTS impl is available here https://bitbucket.org/pulquero/sesame-geosparql-jts (in Maven central).

2) enhanced query support. If I write a query involving geof:distance(?x,?y) < 5, it is basically gonna result in N^2 comparisons. The FTS sails offer optimised support for these types of queries by making using of the geo data indexing features available in the underlying search index.

The testsuite and unit tests provide good examples of what data and common queries look like.

**Comment by jinjin304616** [comment]
Thanks for get back to me so quickly. I attached my ontology which including GeoSparql ontologies and some data instances. I also attached a copy of my code for your reference.

The data I have inside the ontology file is a list of points and polygons. I want to query which points are within which polygons.
Right now I’m using OWL2 API and Jena in the java code to query some attributes. But I can’t use the functions in GeoSparql that’s because Jena doesn’t support GeoSparql. If you can help me figure out how to use GeoSparql with rdf4j Geosparql Jar, that would be great. Thanks.

PS. I’m a PhD student from Curtin University. Is any other way to contact you rather than github?


Best regards,
Feiyan

**Comment by pulquero** [comment]
See this commit: https://github.com/eclipse/rdf4j/commit/e19d805d20a79d89865f2a24ac58d2903cbbe4bf#diff-3e89d5055324404d858a0d413761b1b1R120

**Comment by jinjin304616** [comment]
Thanks for your reply. But what this commit about? I’m not from computer science background, I can’t understand what’s this useful for me.
Besides, in your last reply “a bunch of functions. Add the jar to the classpath and they should be available.” I did add the jar file in my dependencies, but still can’t make it work for me. Could you give me an example please.

**Comment by pulquero** [comment]
The commit shows my email address.

An example would be
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix wkt: <http://www.opengis.net/ont/geosparql#>

select *
{
bind(
geof:distance("POINT (48.8582 2.2945)"^^wkt:wktLiteral, "POINT (48.8738 2.2950)"^^wkt:wktLiteral, http://www.opengis.net/def/uom/OGC/1.0/metre)
as ?d)
}
To be precise you need to ensure the geosparql-queryalgebra jar is on the classpath.

**Comment by jinjin304616** [comment]
Hi Jeen, pulquero had help me identified the problem as follow:
Hi, I see where your problem is. RDF4J is not compatible with Jena - you will either have to switch to using RDF4J and find an OWL reasoner for RDF4J/Sesame, or write some sort of adapter so that Jena understands RDF4J functions. If you mention this on GitHub, Jeen should be able to point you in the direction of an OWL reasoner (I think OWLIM might work but will upgrading to RDF4J).

would you be able to help me with that?

**Comment by jeenbroekstra** [comment]
@jinjin304616 we may be able to help you, but this goes a bit beyond the scope of this issue (which is about providing documentation for GeoSPARQL). I suggest you write an e-mail to explain your situation and the problem to the [rdf4j-users](https://groups.google.com/d/forum/rdf4j-users) mailinglist, and we can continue the discussion there.

**Comment by jinjin304616** [comment]
Thanks, i'll email to the rdf4j-users. At the meanwhile, it will be good if a documentation for GeoSparql can be produced. I‘ve played with RDF4J recently, but I feel it is not as friendly as Jena and the tutorials online are not very clear hence I still haven't gotten the hint of it, not to mention the use of GeoSparql with RDF4J as well.

**Comment by jeenbroekstra** [comment]
@jinjin304616 feel free to make suggestions for improvements in the tutorials (can also be sent to the rdf4j-users list).
