### ISSUE TITLE
Declare our Public API for use with semantic versioning

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#619]
We are aiming to apply [semantic versioning](http://semver.org/), and to a large degree already follow its principles. However, a requirement of SemVer is that we have explicitly specified what our public API is.  

Clearly, not every public class/method in the RDF4J code base is considered part of the public API - some of these are "internal", and are declared public for technical reasons rather than a statement that every user can/should use them and rely on their behavior to remain unchanged for minor/patch versions.

A good starting point is that all "...-api" modules and all public interfaces are considered part of the public API. But we'll need to go further than that - I assume at least a large part of the abstract implementations and a lot of utility code and _some_ public classes should be considered part of the public API as well.

Two main questions:
1. what's the best way to document/specify what we consider the RDF4J public API?
2. which parts of the code base should be part of it?

**Comment by ansell** [comment]
As you say the -api modules are a given for consideration, although the ".impl" or ".util" packages within them could be off limits if they are only intended to be used by other RDF4J modules.

The repository-sail module is a substantially reused link between the 

There is a clear service driven access service to the specific parser modules within rio along with extensive configuration options that should make it possible to leave the individual parser implementations and entire modules off the public API. However, given that they are reused and overridden by third-parties, we should still take them into account and try hard to deprecate signatures in them rather than remove signatures.

The service driven creation and configuration for the sail and repository APIs are not as broadly used and almost all calls into them are done through constructors for the various Sail/Repository implementations. So it may require some modification to the service driven approach for those to make them a little simpler and more broadly used before pushing those constructors to the internal API.

In terms of programmatic verification of the API before releases, one recent tool that we could look at is: 

https://github.com/siom79/japicmp

Another is the animal sniffer maven plugin:

http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/

It may be useful to put removals to a broader public API off until a major version bump such as 3.0 and work with deprecations solely before then.

**Comment by jeenbroekstra** [comment]
I've done several attempts to build a draft spec of what is considered "in" and "out" of our public API, but I must admit I'm struggling to make any rules that stop short of enumerating every single package. 

I think we should approach this differently: rather than trying to come up with a complex definition of what constitutes our public API, we should just make it general rule that _any_ interface, class or method that is publicly accessible is part of our public API, unless _specifically_ specified that it isn't (in which case, this should be in the javadoc of the class and its methods, and we can cover them as exceptions in any automated tooling that we use for compatibility audits). 

Following on from that principle, we should look at our architecture, and identify cases where we'd prefer things are not considered part of the API, but currently (with this rule) they are. 

I am not sure there are actually many such cases, except perhaps the code in the rdf4j-tools repo: the `rdf4j-console`, `rdf4j-http-workbench`, and `rdf4j-http-server` modules are clearly not intended for developer reuse but for end-user functionality only. 

@ansell , @barthanssens, @hmottestad can you name any other concrete examples where a class, a method or a package is currently declared public yet it really _shouldn't_ be considered part of our public API for SemVer purposes?

**Comment by hmottestad** [comment]
All the AST and operators in the SHACL engine as public classes. But I change method signatures and remove things without warning.

**Comment by hmottestad** [comment]
Btw. Java 9 solves this problem with modules. You can have everything public, but only export a single class as part of the module.

**Comment by jeenbroekstra** [comment]
> All the AST and operators in the SHACL engine as public classes. But I change method signatures and remove things without warning.

It's also a good example where making them package-private is no real solution (as the SHACL engine itself wouldn't be able to access them then). Fwiw we have been able to get away with being cavalier about this sofar since SHACL support itself is clearly in beta stage. We'll need to be a little more diligent once that solidifies though. 

Is marking them "internal only" in the javadoc enough? Or is there some other mechanism we can use to make it clear that these are _not_ part of our public API? 

The same argument goes for the SPARQL and SeRQL ASTs, to some degree. An additional complication there is that we offer default implementations of syntax tree visitors, which are _clearly_ meant for public use.

> Btw. Java 9 solves this problem with modules. You can have everything public, but only export a single class as part of the module.

Unfortunately I don't expect us to be able to drop Java 8 support any time soon - there's just too many people and companies that are wary of upgrading past Java 8.

**Comment by hmottestad** [comment]
I don't think adding module definitions would break java 8 compatibility.

Marking classes as internal only may be the way to go.

**Comment by barthanssens** [comment]
Too bad that there is no "Experimental" annotation (or @Deprecated with an optional reason...)


Bart

________________________________

**Comment by ansell** [comment]
Adding module definitions (`module-info.java`) means you need to compile with Java-9+ (likely Java-11 at this point) *and* work through all upstream dependencies that have not yet converted, but you can create Java-8 libraries so downstream can still be Java-8+ rather than Java-9+.

Projects that want to label things as Experimental have made up their own annotations in the past such as this from RxJava: 

https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/annotations/Experimental.java

**Comment by ansell** [comment]
There is a potential modularisation approach using a maven plugin to add `module-info` while staying on JDK8 for builds, that may be appropriate here, but I haven't tested it. I noticed it on the Jackson build files originally:

https://github.com/moditect/moditect

**Comment by jeenbroekstra** [comment]
I'm going to give the "Experimental" / "InternalOnly" annotation a go - I want to check what it looks like in Javadoc etc.

**Comment by jeenbroekstra** [comment]
It can show up in the javadoc, but it's not particularly "in your face": 

![Screenshot from 2019-07-28 15-55-10](https://user-images.githubusercontent.com/728776/62002875-39fea300-b150-11e9-8c55-318b4adb0817.png)

When you click through on the annotation you do see the details of course:
![Screenshot from 2019-07-28 15-55-54](https://user-images.githubusercontent.com/728776/62002884-73cfa980-b150-11e9-9529-0bef0fd143e2.png)

This is what it looks like on a method:

![Screenshot from 2019-07-28 15-54-00](https://user-images.githubusercontent.com/728776/62002878-408d1a80-b150-11e9-8706-ad01d6175260.png)

Can I get a vote on whether this is good enough in the  short term? In future we could either do some javadoc customization (with taglets) or just switch completely to using modules. The main thing is that we have _some_ way to communicate that certain things are not part of the Public API (despite being public).

**Comment by jeenbroekstra** [comment]
An alternative is, of course, that we don't use any custom annotations at all, but instead simply mark things that are public but not for external use / experimental with a `@deprecated` javadoc tag (instead of an annotation) - in which we can specify a reason.

For example:

```
/**
 * @author Jeen
 * 
 * @deprecated this feature is for internal use only: its existence, signature or behavior may change without warning
 *             from one release to the next.
 */
public class OldExistingClassThatShouldNotBeUsed {
....
}
```

or even:

```
/**
 * @deprecated this feature is experimental: its existence, signature or behavior may change without warning
 *             from one release to the next.
 */
public class HotNewFeature { }
```

Large advantage of this is that in most IDEs this will be shown as a warning whenever someone tries to use the class/method (which is not something we can achieve with a custom tag).

**Comment by jeenbroekstra** [comment]
I've done a first pass over the code base to introduce both deprecation and the custom annotations where I think we want to indicate that something is _not_ part of the public API.

I'd like to hear from you what other classes you think should get this kind of annotation.

**Comment by jeenbroekstra** [comment]
I'm marking this as closed since we have done what we can for now: we are using custom annotation to mark things as `@InternalUseOnly` and/or `@Experimental`.
