### ISSUE TITLE
SesameSession does not apply any custom http headers set by additionalHeaders 

### ISSUE THREAD

**Issue by damyan-ognyanov** [eclipse/rdf4j#764]
SesameSession overrides getQueryMethod/getUpdateMethod but it does not apply the values from additionalHeaders field. The result is that the client app could not use that functionality. SparqlSession does do that.

**Comment by jeenbroekstra** [comment]
Be aware that in RDF4J 2.2, SesameSession was refactored and renamed (to RDF4JProtocolSession). See #721 . 

If you want this fixed in a 2.1.x patch release, we will need to create a release branch (from the 2.1.6 tag) before you can patch it. In addition, when merging the fix back into master there will probably need to be some manual labor to move the fix to the correct class.

The simplest would be not do a 2.1.7 patch, but to fix this as part of a 2.2.1 patch instead.
