### ISSUE TITLE
Parser produces non-canonical integer when parsing math '+' expression

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#77]
(Migrated from https://openrdf.atlassian.net/browse/SES-2234 )

This query:

{code}
PREFIX ex: <ex:>

ASK WHERE {
    ?this ex:score ?score .
    FILTER (!(?score+5 != 0)) .
}
{code}

produces the following algebra expression:

{code}
Slice ( limit=1 )
   Filter
      Not
         Compare (!=)
            MathExpr (+)
               Var (name=score)
               ValueConstant (value="+5"^^http://www.w3.org/2001/XMLSchema#integer)
            ValueConstant (value="0"^^http://www.w3.org/2001/XMLSchema#integer)
      StatementPattern
         Var (name=this)
         Var (name=_const-313ecd0b-uri, value=ex:score, anonymous)
         Var (name=score)
{code}

The value constant representing the integer 5 incorrectly has a '+' sign prepended - presumably because the parser incorrectly processes the + math operator as part of the integer value. 

Although this causes no problems in normal operation of the SPARQL engine, it is an issue in work by [~pulquero] on a SPIN engine.

**Comment by josephw** [comment]
This is due to the definition of `AdditiveExpression` in `sparql.jjt`. One possible production is:

    MultiplicativeExpression()
    NumericLiteralPositive() {jjtThis.setOperator(MathOp.PLUS);} #Math(2)

i.e., a positive number next to the first expression is implicitly treated as addition. This means that the `+` is part of the image of the `NumericLiteralPositive`.

The simplest fix would be to drop any leading `+` on creating the `Value` for any numeric literal. This might surprise in the case of `1 + +2`, but that seems questionable.

The JJTree files don't seem to be transformed into `.java` at compile time, so the build might need a tweak before grammar changes would be easy to test with.
