### ISSUE TITLE
SPARQL Construct Union duplicated results

### ISSUE THREAD

**Issue by skodapetr** [eclipse/rdf4j#857]
Using Rdf4j version 2.2.2:

RDF-FILE.ttl:
```
<https://1> 
    <http://text> "A" ;
    <http://iri> <https://3> .	

<https://2> 
	<http://text> "B" ;	
	<http://iri> <http://4> .
```

Java code:
```java
    private static final String QUERY = ""
            + "CONSTRUCT { <http://1> <http://reference> ?s } WHERE {"
            + "{ ?s ?p ?o .  FILTER isIRI(?o) } UNION { ?s ?p ?o . FILTER isLiteral(?o) }"
            + "}";
    
    public static void main(String[] args) throws Exception {
        Repository repository;
        repository = new SailRepository(new MemoryStore());
        repository.initialize();
        File file = new File("RDF-FILE.ttl");
        try (RepositoryConnection connection = repository.getConnection()) {
            connection.add(file, "http://base", RDFFormat.TURTLE);
        }
        Repositories.consume(repository, (connection) -> {
            GraphQueryResult res = connection.prepareGraphQuery(QUERY).evaluate();
            while (res.hasNext()) {
                Statement st = res.next();
                System.out.println(st.getObject());
            }
        });
        repository.shutDown();
    }
```

Output:
```
https://1
https://2
https://1
https://2
```
As the subject and predicate are hard coded in the query, this actually means that the output contains duplicated statements. I believe that the result should be only
```
https://1
https://2
```
[specification](https://www.w3.org/TR/sparql11-query/#construct) says ```The result is an RDF graph formed by taking each query solution in the solution sequence, substituting for the variables in the graph template, and combining the triples into a single RDF graph by set union```

The duplicated statements can be filtered out using ```equals```.  So a possible workaround is:
```java
        Set<Statement> hs = new HashSet<>();
        Repositories.consume(repository, (connection) -> {
            GraphQueryResult res = connection.prepareGraphQuery(QUERY).evaluate();
            while (res.hasNext()) {
                hs.add(res.next());
            }
        });
        for (Statement st : hs) {
            System.out.println(st.getObject());
        }
```

**Comment by elky87** [comment]
This is a known issue, see https://github.com/eclipse/rdf4j/issues/515

But I disagree with the linked ticket. I think 'Construct' should dedup. When we look at the last part of the construct spec "combining the triples into a single RDF graph by **set union**".  A set union should remove duplicates IMHO.

**Comment by jakubklimek** [comment]
OK, I also disagree with #515 conclusion with the same argument. Should we reopen it?

**Comment by elky87** [comment]
I don't know how to but I would vote to re-open https://github.com/eclipse/rdf4j/issues/515

**Comment by jakubklimek** [comment]
The same happens in RDF4J workbench when the data is uploaded to an empty in memory store, for example, and the query
```
CONSTRUCT { <http://1> <http://reference> ?s } 
WHERE {
{ ?s ?p ?o .  FILTER isIRI(?o) } UNION { ?s ?p ?o . FILTER isLiteral(?o) }}
```
is run:
![image](https://user-images.githubusercontent.com/718827/27541296-b457f9ec-5a83-11e7-9eb3-ce48c09a5668.png)

**Comment by jeenbroekstra** [comment]
There already is a utility for this: `QueryResults.distinctResults()`.

**Comment by jeenbroekstra** [comment]
There is also a (documented) parameter in the REST API to force distinct results. A possible improvement to the Workbench would be a checkbox to enable that option. 

But making the query engine return distinct results by default is not a good idea. The current behavior is not contrary to the spec, in 99% of cases the fact that you get  duplicates is not relevant because subsequent processors (RDF writers, Model objects, etc) filter them out, and the performance penalty inherent in having to dedupe every CONSTRUCT query result is just not acceptable for those corner cases where it is an issue (especially since for those corner cases acceptable options exist to force deduplication).

**Comment by gwcox66** [comment]
I'm observing this same issue when using SPIN constructors under RDF4J.  In that case, there is no other processing to remove the duplicates.  Instead, I get multiple artifacts in the knowledge base when I should have one.  This is evident when the `CONSTRUCT ` contains blank nodes since a new blank node is created and asserted for each of the duplicate responses.  In my case, I typically see three responses when I should see one.   When debugging my `WHERE ` clause with a `SELECT DISTINCT *` I see duplication as well, which does seem to run contrary to the `DISTINCT ` directive.  Note that I'm forcing the inclusion of the `sp:text` in order to have RDF4J execute my SPIN rules from the source rather from the RDF since that seems to avoid a set of other bugs.
