### ISSUE TITLE
usage of null with varargs in methods

### ISSUE THREAD

**Issue by seralf** [eclipse/rdf4j#878]
Hi I have some doubt about the usage of varargs for handling contexts in some methods from connection, for example for the method `clear` we could write something like:

```
Repository repo = new SailRepository(new MemoryStore());
repo.initialize();
RepositoryConnection conn = repo.getConnection();

// 1
conn.clear();
// 2
conn.clear(null);
// 3
conn.clear(new Resource[]{});

conn.close();
Repo.shutdown();
```

I expected the three methods to have a similar behaviour, but instead something like the last (3) option seems not having effects at all.
Am I missing something? 

Even if it may sound strange, I would expect passing an array without elements to have the same meaning of passing null: this would be helpful when calling methods from Scala (and similarly I'd expect in Java 8), when usually the adoption of null is discouraged.

What do you think about? Thanks in advance for any comments or suggestion

**Comment by barthanssens** [comment]
Well, one could argue this is the intended behavior, because 3) is a list/array of contexts that just happens to be empty.

Say you have an application that stores e.g. submitted form data in separate named graphs / contexts, and from time to time old info needs to be deleted. You run a query to get old contexts, and provide the list to `con.clear()`, and the triples get deleted.
However, the list may be empty (no old context found), but in this cause you don't want to clear the entire repository (of course, you can also argue that in this example checking for an empty list should be done before passing the list to con.clear)

**Comment by jamesrdf** [comment]
clear() and clear(new Resource[]{}) should both clear all contexts, if this is not the case please provide a more detailed example.

Whereas clear(null) and clear((Resource)null) and clear((Resource[])null) and clear(new Resource[]{null}) should either clear only the null context or throw IllegalArgumentException.
