### ISSUE TITLE
Precise calculation of SimpleLiteral.toString() length

### ISSUE THREAD

**Issue by yasengmarinov** [eclipse/rdf4j#948]
Currently the initial length of the StringBuilder used in SimpleLiteral.toString() is not precise enough resulting in a lot of array resizing when the Literal is with short label.

**Comment by ansell** [comment]
Why is ``SimpleLiteral.toString`` performance sensitive if it isn't quoting its results? It shouldn't be on any performance sensitive codepaths if it isn't following a particular syntax to consistently quote its value. Are users presuming incorrectly that it can be used for either Turtle/N-Triples or SPARQL because its results look similar?

This issue is the reason that Commons RDF explicitly has a method named ``ntriplesString`` to unambiguously provide a simple way to get a safely encoded string representation in a widely parseable format https://github.com/apache/commons-rdf/blob/master/commons-rdf-api/src/main/java/org/apache/commons/rdf/api/RDFTerm.java#L55

**Comment by jasskata** [comment]
Hi Peter,
We are using Value.toString() to generate custom hash-es. So we do not rely
on a particular syntax returned by the method.
