### ISSUE TITLE
add Rio WriterConfig setting for using single quotes in XML

### ISSUE THREAD

**Issue by grexe** [eclipse/rdf4j#992]
Esp. when wrapping the RDF XML in, e.g., a JSON result, it would be handy to use single quotes instead of double quotes to avoid unnecessary escaping the quotes in the JSON with \".
Sadly there is no config setting in RIO's Writer that supports this.

E.g. I would prefer this:
```
<?xml version='1.0' encoding='UTF-8'?>
<rdf:RDF
	xmlns:ppx='http://schema.semantic-web.at/ppx/'
	xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'
	xmlns:skos='http://www.w3.org/2004/02/skos/core#'
	xmlns:ctag='http://commontag.org/ns#'
	xmlns:dcterms='http://purl.org/dc/terms/'>
```
to this:
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rdf:RDF\n\txmlns:ppx=\"http://schema.semantic-web.at/ppx/\"\n\txmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n\txmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n\txmlns:ctag=\"http://commontag.org/ns#\"\n\txmlns:dcterms=\"http://purl.org/dc/terms/\">
```

**Comment by barthanssens** [comment]
Hi,

I'm currently working on this issue, but I guess you also need an option to escape the selected (single/double) quotes in the text nodes of the XML, not only the quotes around the attribute values ?

**Comment by grexe** [comment]
yes you're right, ideally this would be handled, too. E.g. take the "opposite" quote for texts to avoid escaping as much as possible.

**Comment by barthanssens** [comment]
Well, the quotes before and after the attribute value can of course be either single or double quotes,

But the correct way to handle this _within_ text (also within attribute values) is to use entities like \&apos; , instead of replacing double quotes by single quotes (or the other way round).
Otherwise you're changing the text, which in turn may produce strange results when displaying texts in various languages (English: e.g. I'll => I"ll, French: e.g. l'été, Dutch...)
