### ISSUE TITLE
LOAD query gives the message "Missing parameter: query"

### ISSUE THREAD

**Issue by BorderCloud** [eclipse/rdf4j#993]
Hello

I tried to evaluate the interoperablity of rdf4j 2.2.4 but I have the message "Missing parameter: query" with my  LOAD queries. 

Example :
```
Error query  : LOAD <http://w3c.github.io/rdf-tests/sparql11/data-sparql11/delete/delete-post-01f.ttl>
Data POST 
(
    [update] => LOAD <http://w3c.github.io/rdf-tests/sparql11/data-sparql11/delete/delete-post-01f.ttl>
    [Accept] => application/sparql-results+xml
)
Error endpoint: http://172.17.0.2:8080/rdf4j-server/repositories/test
Error http_response_code: 400
Error message: Missing parameter: query
```
You can see these tests in this project : https://travis-ci.org/BorderCloud/tft-rdf4j

It's a bug ? or LOAD is not supported for the moment ?

Thanks

**Comment by barthanssens** [comment]
Hi,

Does the test script sends the header `Content-Type: application/sparql-update` in the POST request ?
(The "missing query" message indicates that the server was actually expecting an `application/x-www-form-urlencoded` message, instead of an unencoded query.)

Best regards

**Comment by jeenbroekstra** [comment]
Came across this during backlog cleanup. Since this is quite old I assume it's no longer relevant, but: it looks as if an incorrect endpoint URL is used. RDF4J Server has separate endpoints for queries and updates. This looks like you're trying to send the LOAD operation to the query endpoint, rather than the update endpoint `http://172.17.0.2:8080/rdf4j-server/repositories/test/statements` . See https://rdf4j.org/documentation/rest-api/#repository-statements for details.

**Comment by cristianstanescu** [comment]
Even old, can still be relevant for newcomers. For the ref, updated documentation link: https://rdf4j.org/documentation/reference/rest-api/#repository-statements
